---
- name: Add Redis apt repo
  apt_repository: repo='ppa:chris-lea/redis-server' state=present
  register: add_redis_repo

- name: Update package list
  apt: update_cache=yes
  when: add_redis_repo|changed

- name: Install the Redis packages
  apt: name="{{ item }}" state=present
  with_items: "{{ redis_ubuntu_pkg }}"
  environment: env

- name: Copy the redis configuration file 
  template: src=redis.conf.j2 dest="{{ redis_conf_dest }}"
  notify: 
   - restart redis 

- name: Copy the rsyslogd configuration file for redis filter
  template: src=rsyslogd.conf.j2 dest=/etc/rsyslog.d/redis.conf
  when: redis_syslog_enabled == "yes"
  notify:
  - restart rsyslog

- name: Set the kernel paramter for vm overcommit 
  sysctl: name=vm.overcommit_memory value="{{ redis_overcommit_memory }}" state=present

- name: start the redis service
  service: name="{{ redis_service }}" state=started enabled=yes
  tags: after-reboot

- name: redis monit config
  sudo: yes
  template:
    src: "monit.redis.j2"
    dest: "/etc/monit/conf.d/redis"
    group: root
    owner: root
    mode: 0640
  notify: reload monit
  tags: monit

- monit:
    name: redis
    state: monitored
  tags: monit
