sudo_user: cchq
default_branch: master
home: "/home/cchq"
project: commcare-hq
code_repo: 'https://github.com/dimagi/commcare-hq.git'
timing_log: null  # make a file path to log deploy timing to it. e.g. '../fabric-timing.txt'
keepalive: 60
ignore_kafka_checkpoint_warning: False
acceptable_maintenance_window: null
email_enabled: True
deploy_event_url: null
