formplayer_build_dir: "{{ code_home }}/formplayer_build"
formplayer_data_dir: "{{ encrypted_root }}/formplayer"
# formplayer_sentry_dsn: ..defined in secret file
# formplayer_db_name: ..defined in secret file

