---
dependencies:
  - role: java
    java_packages:
      - openjdk-7-jdk
    java_bin_path: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin
    when: ansible_distribution_version == '14.04'
      
  - role: java
    java_packages:
    when: ansible_distribution_version == '18.04'
  
