---
# cchq user is created in commcarehq
- name: Add dev group
  sudo: yes
  group: name={{ dev_group }} state=present

- name: Add dev users
  sudo: yes
  user: name={{ item.name }} state=present shell=/bin/bash groups={{ dev_group }}
  with_items: dev_users.present

- name: Remove dev users
  sudo: yes
  user: name={{ item.name }} state=absent
  with_items: dev_users.absent

- name: Add ansible user
  user: name=ansible state=present shell=/bin/bash groups="sudo" password={{ ansible_user_password }}

- name: Add public keys
  sudo: yes
  authorized_key: user={{ item.name }} state=present key="{{ item.key }}"
  with_items: dev_users.present

- name: find supervisorctl path
  shell: 'dirname "$(which supervisorctl)"'
  register: dirname_which_supervisorctl
  changed_when: false

- name: Copy sudoers file
  sudo: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/cchq validate='visudo -cf %s' owner=root group=root mode=0440

# ansible used to create this file
# but for consistency with prod machines, we changed to 'cchq'
- name: remove cchq_sudoers
  file: state=absent path=/etc/sudoers.d/cchq_sudoers
