---
- name: Add dev group
  become: yes
  group: name="{{ dev_group }}" state=present

- name: Add users for current devs
  become: yes
  user: name="{{ item }}" state=present shell=/bin/bash groups={{ dev_group }}
  with_items: '{{ dev_users.present }}'

- name: Add public keys for current devs
  become: yes
  authorized_key: user="{{ item }}" state=present key="{{ lookup('file', 'vars/users/' ~ item ~ '.pub') }}" exclusive=yes
  with_items: '{{ dev_users.present }}'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add cchq user
  become: yes
  user: name="{{ cchq_user }}" state=present shell=/bin/bash groups={{ dev_group }} append=yes
  tags: commcarehq

- name: Remove public key for cchq user
  become: yes
  authorized_key: user="{{ cchq_user }}" key='' state=present exclusive=yes
  tags: commcarehq

- name: Add MSP user sudo user
  user: name="{{ item.value.username }}" state=present shell=/bin/bash groups="sudo" password="{{ item.value.password }}"
  when: msp_users|default(false)
  with_dict: '{{ msp_users }}'

- name: Add public key for MSP
  become: yes
  authorized_key: user="{{ item.value.username }}" state=present key="{{ lookup('file', 'vars/{{ deploy_env }}/{{ item.value.username }}.pub') }}"
  when: msp_users|default(false)
  with_dict: '{{ msp_users }}'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add ansible user
  user: name=ansible state=present shell=/bin/bash groups="sudo" password="{{ ansible_user_password_sha_512 }}"

- name: Authorize current devs to login as ansible
  become: yes
  authorized_key: user=ansible state=present key="{{ lookup('file', 'vars/users/' ~ item ~ '.pub') }}"
  with_items: '{{ dev_users.present }}'

- name: De-authorize ansible pubkey
  become: yes
  authorized_key: user=ansible state=absent key="{{ lookup('file', 'vars/users/ansible.pub') }}"

- name: find supervisorctl path
  shell: 'dirname "$(which supervisorctl)"'
  register: dirname_which_supervisorctl
  changed_when: false
  check_mode: no

- import_tasks: remove_users.yml
  when: dev_users.absent

- name: Copy sudoers file
  become: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/cchq validate='visudo -cf %s' owner=root group=root mode=0440
