postgresql_version: '9.4'
postgresql_cluster_name: 'main'
postgresql_port: 5432
postgresql_ssl_enabled: False
postgresql_dir_original_path: /var/lib/postgresql
postgresql_dir_path: "{{ encrypted_root }}/postgresql"
postgresql_backup_dir: "{{ encrypted_root }}/backups/postgresql"
postgresql_home: "{{ postgresql_dir_path }}/{{ postgresql_version }}/main"
postgresql_config_home: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_pid_file: "{{ postgresql_dir_path }}/{{ postgresql_version }}-main.pid"
postgres_install_dir: "/usr/lib/postgresql/{{ postgresql_version }}"
postgresql_archive_dir: "{{ postgresql_dir_path }}/wal_archive"
postgresql_log_directory: "{{ postgresql_home }}/pg_log"
postgresql_num_logs_to_keep: 20

pgbouncer_port: 6432
pgbouncer_pid_file: "/var/run/postgresql/pgbouncer.pid"
pgbouncer_config_home: /etc/pgbouncer
pgbouncer_ini: "{{ pgbouncer_config_home }}/pgbouncer.ini"
pgbouncer_users: "{{ pgbouncer_config_home }}/userlist.txt"

# defaults should match the postgresql defaults
postgresql_max_connections: 20
postgresql_work_mem: '8MB'
postgresql_shared_buffers: '1024MB'
postgresql_max_stack_depth: '2MB'
postgresql_effective_cache_size: '128MB'
postgresql_maintenance_work_mem: '64MB'
postgresql_checkpoint_completion_target: '0.5'
postgresql_wal_buffers: '-1'
postgresql_default_statistics_target: '100'
postgresql_checkpoint_segments: '16'  # V <= 9.4
postgresql_max_wal_size: '256MB'  # V >= 9.6

pgbouncer_max_connections: 100
pgbouncer_default_pool: 15
pgbouncer_reserve_pool: 4
pgbouncer_pool_timeout: 2
pgbouncer_pool_mode: session
