- name: Remove old Hourly Cron job
  become: true
  cron:
    name: "Backup postgres hourly"
    job: "/usr/local/sbin/create_postgres_dump.sh hourly {{ postgresql_backup_hours * 60 }}"
    minute: 0
    hour: "{{ nadir_hour_frequency|default(3) }}"
    weekday: "1,2,3,4,5,6"
    user: postgres
    cron_file: backup_postgres
    state: absent

- name: Remove old Daily Cron job
  become: true
  cron:
    name: "Backup postgres daily"
    job: "/usr/local/sbin/create_postgres_dump.sh daily {{ postgresql_backup_days }}"
    minute: 0
    hour: "{{ nadir_hour }}"
    weekday: "1,2,3,4,5,6"
    user: postgres
    cron_file: backup_postgres
    state: absent

- name: Remove old Weekly Cron job
  become: true
  cron:
    name: "Backup postgres weekly"
    job: "/usr/local/sbin/create_postgres_dump.sh weekly {{ postgresql_backup_weeks * 7 }}"
    minute: 0
    hour: "{{ nadir_hour }}"
    weekday: 0
    user: postgres
    cron_file: backup_postgres
    state: absent

- name: Remove plain backup files
  become: true
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cron.d/create_postgres_dump.sh"
    - "/usr/local/sbin/create_postgres_dump.sh"
    - "/usr/local/sbin/backup_snapshots.py"
    - "/usr/local/sbin/retrieve_backup.py"
    - "/usr/local/sbin/restore_from_backup.sh"
