---
dependencies:
  - {role: common_installs, tags: common_installs}
  - {role: commcarehq, tags: commcarehq}
  - {role: supervisor, tags: supervisor}
  - {role: users, tags: users}
  - {role: ssh, tags: ssh}
  - role: edit
  - {role: ksplice, tags: ksplice}
  - {role: newrelic, tags: newrelic, when: NEW_RELIC_KEY is defined}
