---
dependencies:
  - couchdb2-preinstall
  - role: andrewrothstein.couchdb-cluster
    couchdb_dep_pkgs:
    - build-essential
    - pkg-config
    - esl-erlang=1:21.3.8.2-1
    - libicu-dev
    - libnspr4-dev
    - libcurl4-openssl-dev

  - role: monit
