---
dependencies:
  - couchdb2-preinstall
  - role: andrewrothstein.couchdb-cluster
    couchdb_ver: '{{ couchdb_version }}'
    couchdb_dep_pkgs:
      - build-essential
      - pkg-config
      - libicu-dev
      - libnspr4-dev
      - libcurl4-openssl-dev
      - couch-libmozjs185-dev

  - role: monit
