datadog_custom_dir: "{{ cchq_home }}/datadog"
datadog_parsers_repo: https://github.com/dimagi/datadog-parsers
datadog_parsers_dest: "{{ datadog_custom_dir }}/datadog-parsers"
datadog_parsers:
  - input: "{{ log_home }}/{{ deploy_env }}-timing.log"
    python_file: "{{ datadog_parsers_dest }}/nginx/timings.py"
    python_function: parse_nginx_timings
    hosts: "{{ groups['proxy'] }}"
  - input: "{{ log_home }}/{{ deploy_env }}-timing.log"
    python_file: "{{ datadog_parsers_dest }}/nginx/timings.py"
    python_function: parse_nginx_apdex
    hosts: "{{ groups['proxy'] }}"
  - input: "{{ log_home }}/{{ deploy_env }}-timing.log"
    python_file: "{{ datadog_parsers_dest }}/nginx/timings.py"
    python_function: parse_nginx_counter
    hosts: "{{ groups['proxy'] }}"
  - input: "{{ log_home }}/{{ deploy_env }}_commcare-nginx_error.log"
    python_file: "{{ datadog_parsers_dest }}/nginx/errors.py"
    python_function: parse_nginx_errors
    hosts: "{{ groups['proxy'] }}"
  - input: "{{ log_home }}/{{ localsettings.DEPLOY_MACHINE_NAME }}-commcarehq.couch.log"
    python_file: "{{ datadog_parsers_dest }}/couch/parsers.py"
    python_function: parse_couch_logs
    hosts: "{{ groups['webworkers'] + groups['pillowtop'] + groups['celery'] + groups['django_manage'] }}"
