---

- name: Add cchq user
  sudo: yes
  user: name={{ cchq_user }} state=present shell=/bin/bash generate_ssh_key=yes
  tags: commcarehq

- name: find supervisord path
  shell: 'which supervisord'
  register: which_supervisord
  changed_when: false
  failed_when: which_supervisord.rc != 0 and which_supervisord.rc != 1
  # run in check mode
  always_run: yes

- name: install supervisor
  apt: name=supervisor state=present
  sudo: yes
  when: not which_supervisord.stdout

- name: check for sysvinit conf
  stat: path=/etc/init.d/supervisor
  register: init_d_conf

- name: service stop supervisor
  sudo: yes
  service: name=supervisor state=stopped
  when: init_d_conf.stat.exists

- name: pkill supervisord if run by cchq
  command: pkill -U cchq supervisord
  # if it returns 1 with no output, that just means no process to kill
  register: result
  failed_when: result.rc != 0 and (result.stderr or result.stdout)

- name: remove /etc/init.d/supervisor
  file: state=absent path=/etc/init.d/supervisor
  when: init_d_conf.stat.exists

- name: remove default /etc/supervisor directory
  file: state=absent path=/etc/supervisor

- name: configure supervisor
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf
  sudo: yes

- name: Add Upstart Conf
  sudo: yes
  template:
    src: supervisord.upstart.conf.j2
    dest: /etc/init/supervisord.conf

- name: stop supervisor to pick up configuration changes
  sudo: yes
  command: stop supervisord
  failed_when: no

- name: pkill supervisord if run by cchq
  command: pkill -9 -U cchq
  # if it returns 1 with no output, that just means no process to kill
  register: result
  failed_when: result.rc != 0 and (result.stderr or result.stdout)

- sudo: yes
  command: start supervisord
  failed_when: no
