# CouchDB
- name: Install prequisites
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - g++
    - erlang-base
    - erlang-dev
    - erlang-eunit
    - erlang-nox
    - libmozjs185-dev
    - libicu-dev
    - libcurl4-gnutls-dev
    - libtool

- name: Check CouchDB existence
  stat: path=/usr/local/bin/couchdb
  register: couchdb_path

- name: Download CouchDB source
  sudo: no
  get_url: url=http://mirrors.ibiblio.org/apache/couchdb/source/1.5.1/apache-couchdb-1.5.1.tar.gz dest=~/apache-couchdb-1.5.1.tar.gz
  when: not couchdb_path.stat.exists

- name: Compile + install CouchDB
  shell: "{{ item }}"
  sudo: no
  with_items:
    - tar xvf ~/apache-couchdb-1.5.1.tar.gz
    - cd apache-couchdb-1.5.1 && ./configure
    - make -C ~/apache-couchdb-1.5.1
    - sudo make install -C ~/apache-couchdb-1.5.1
    - sudo rm -rf ~/apache-couchdb-1.5.1*
  when: not couchdb_path.stat.exists

- name: Add CouchDB user
  user: name=couchdb createhome=no password=no state=present

- name: Apply CouchDB config
  template: src=local.ini.j2 dest=/usr/local/etc/couchdb/local.ini

- name: CouchDB ownership permissions
  file: path={{ item }} owner=couchdb group=couchdb recurse=yes state=directory
  with_items:
    - /usr/local/var/log/couchdb
    - /usr/local/var/lib/couchdb
    - /usr/local/var/run/couchdb
    - /usr/local/etc/couchdb/

- name: Configure CouchDB as service
  file: src=/usr/local/etc/init.d/couchdb dest=/etc/init.d/couchdb state=link

- name: Update rc.d
  shell: update-rc.d couchdb defaults

- name: Start CouchDB service
  service: name=couchdb state=started

- name: Add CouchDB databases
  shell: "{{ item }}"
  with_items:
    - curl -X PUT "http://localhost:5984/{{ couchdb_db }}"
    - curl -X PUT "http://localhost:5984/_config/admins/{{ couchdb_user }}" -d '"{{ couchdb_pw }}"'
