# Configure swap file if swap_size variable is present
#
# `swap_size` is intended to be set in the hosts file on an as needed
# basis. Most machines should not have swap.

- name: Check if swap file exists
  stat: path=/swapfile
  register: swapfile
  changed_when: false
  failed_when: false
  check_mode: no
  tags: swap

- name: Create swap space
  become: true
  command: fallocate -l {{ swap_size }} /swapfile
  when: swap_size is defined and not swapfile.stat.exists
  tags: swap

- name: Set swap file mode
  become: true
  file: path=/swapfile state=file mode=600
  when: swap_size is defined and not swapfile.stat.exists
  tags: swap

- name: Make swap
  become: true
  command: mkswap /swapfile
  when: swap_size is defined and not swapfile.stat.exists
  tags: swap

- name: Add swap to fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: "^/swapfile"
    line: "/swapfile none swap sw 0 0"
    state: present
  when: swap_size is defined and not swapfile.stat.exists
  tags: swap

- name: Turn on swap
  become: true
  command: swapon -a
  when: swap_size is defined and not swapfile.stat.exists
  tags: swap

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
  become: true
  tags: swap

# below are commands to remove swap if swap_size is removed from the config

- name: Remove swap from fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: "^/swapfile "
    state: absent
  when: swap_size is not defined and swapfile.stat.exists
  tags: swap

- name: Turn swap off
  become: true
  shell: swapoff -a
  when: swap_size is not defined and swapfile.stat.exists
  tags: swap

- name: Remove swap file
  become: true
  file: path=/swapfile state=absent
  when: swap_size is not defined and swapfile.stat.exists
  tags: swap
