pgbouncer_port: 6432
pgbouncer_pid_file: "/var/run/postgresql/pgbouncer-{{ item }}.pid"
pgbouncer_config_home: /etc/pgbouncer
pgbouncer_ini: "{{ pgbouncer_config_home }}/pgbouncer-{{ item }}.ini"
pgbouncer_users: "{{ pgbouncer_config_home }}/userlist-{{ item }}.txt"
pgbouncer_socket_dir: "/var/run/postgresql/pgbouncer-{{ item }}"
pgbouncer_log_file: "/var/log/postgresql/pgbouncer-{{ item }}.log"

pgbouncer_max_connections: 100
pgbouncer_default_pool: 15
pgbouncer_reserve_pool: 4
pgbouncer_pool_timeout: 2
pgbouncer_pool_mode: session
pgbouncer_kernel_settings: {}

pgbouncer_client_tls_key_file: ~
pgbouncer_client_tls_cert_file: ~

postgresql_port: 5432
