formplayer_sentry_dsn: ''
# define this to turn on archiving
# (you can't use s for seconds, but m, h, d work for minute, hour, day)
# formplayer_archive_time_spec: '10m'
formplayer_purge_time_spec: '2d'
# setting `_should_update_formplayer_in_place` to `yes`
# will result in formplayer updating in place instead of through a release / symlink sequence.
# Unless tasks are further filtered (i.e. with a tag), this can cause unncessary downtime.
# This variable should never be set in public.yml,
# and is only meant to be used by update-config
_should_update_formplayer_in_place: no
formplayer_data_dir: "{{ encrypted_root }}/formplayer"
use_monit_for_formplayer: false
