# Base env containing default values which get
# overridden or added to in each of the specific envs below.
---
base:
  sudo_user: cchq
  django_bind: 0.0.0.0
  django_port: 9010
  flower_port: 5555
  gunicorn_workers_factor: 1
  gunicorn_workers_static_factor: 0
  home: "/home/cchq"
  project: commcare-hq
  code_repo: 'git://github.com/dimagi/commcare-hq.git'
  timing_log: null  # make a file path to log deploy timing to it. e.g. '../fabric-timing.txt'
  jython_memory: "3584m"
  formplayer_memory: "3584m"
  keepalive: 60
  http_proxy: null
  newrelic_javaagent: False

softlayer:
  environment: softlayer
  formplayer_memory: "7000m"
  newrelic_javaagent: True
  celery_processes:
    '*':
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
        server_whitelist: 10.162.36.233
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 50
      async_restore_queue:
        concurrency: 4
      flower: {}


icds:
  environment: icds
  http_proxy: 169.38.84.79:3128
  gunicorn_workers_factor: 2
  gunicorn_workers_static_factor: 1
  celery_processes:
    '*':
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
        server_whitelist: 10.247.24.19
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 3
      async_restore_queue:
        concurrency: 4
      flower: {}


production:
  environment: production
  newrelic_javaagent: True

  celery_processes:
    hqcelery0:
      periodic:
        server_whitelist: hqcelery0.internal-va.commcarehq.org
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      email_queue:
        concurrency: 2
      repeat_record_queue:
        concurrency: 200
      ucr_queue:
        concurrency: 4
    hqcelery1:
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 8
      logistics_reminder_queue:
        concurrency: 2
      logistics_background_queue:
        concurrency: 2
      async_restore_queue:
        concurrency: 4
      flower: {}
    hqcelery2:
      main:
        concurrency: 8
      saved_exports_queue:
        concurrency: 3
      background_queue:
        concurrency: 4

staging:
  environment: staging

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      pillow_retry_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}

swiss:
  environment: swiss
  jython_memory: "1024m"
  formplayer_memory: "1024m"

  service_blacklist:
    - supervisor_websockets.conf
    - supervisor_formplayer_spring.conf

  celery_processes:
    '*':
      main:
        concurrency: 1
      background_queue:
        concurrency: 1
      periodic:
        concurrency: 1
        server_whitelist: swiss.commcarehq.org
      repeat_record_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 1
      pillow_retry_queue:
        concurrency: 1
      ucr_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 1
      reminder_queue:
        concurrency: 1
      reminder_rule_queue:
        concurrency: 1
      sms_queue:
        concurrency: 1
      async_restore_queue:
        concurrency: 1
      flower: {}
