datadog_integration_redisdb: true
redis_version: 4.0.8
redis_install_dir: "/opt/redis/{{ redis_version}}"
redis_dir: "{{ encrypted_root }}/redis"
redis_local_facts: false
redis_logfile: "{{ redis_dir }}/redis.log"
redis_service_name: redis-server
redis_syslog_enabled: "yes"
# This implements the best practice of setting redis_maxmemory to half the RAM
# Discussion: https://github.com/dimagi/commcare-cloud/pull/2929#issuecomment-499970466
redis_maxmemory: "{{ ansible_memory_mb.real.total // 2 }}m"
redis_maxmemory_policy: volatile-lru
redis_save: []
redis_appendonly: "yes"
redis_timeout: 300  # 5 minutes
cluster_config:
  cluster-enabled: "yes"
  cluster-config-file: "nodes.conf" # Redis internal filename, never change this
  cluster-node-timeout: "5000"
check_master_script_path: "{{ redis_install_dir }}/redis_is_master
