---
- name: Copy replication credentials
  become: yes
  template:
    src: "plain/pgpass.j2"
    dest: "{{ postgresql_dir_original_path }}/.pgpass"
    group: postgres
    owner: postgres
    mode: 0600
    backup: yes

- name: Copy postgres backup script
  become: yes
  template:
    src: "plain/create_postgres_dump.sh.j2"
    dest: "/usr/local/sbin/create_postgres_dump.sh"
    group: postgres
    owner: postgres
    mode: 0700
    backup: yes

- name: install boto3
  become: yes
  pip:
    name: boto3
    version: 1.4.0
  when: postgres_s3

- name: Create aws config directory
  become: yes
  file:
    path: '{{ postgresql_dir_original_path }}/.aws'
    owner: postgres
    group: postgres
    mode: 0755
    state: directory
  when: postgres_s3
    
- name: copy boto3 credentials file
  become: yes
  template:
    src: "plain/aws_credentials.j2"
    dest: "{{ postgresql_dir_original_path }}/.aws/credentials"
    group: postgres
    owner: postgres
    mode: 0700
    backup: yes
  when: postgres_s3
  
- name: Copy s3 upload script
  become: yes
  template:
    src: "plain/backup_snapshots.py.j2"
    dest: "/usr/local/sbin/backup_snapshots.py"
    group: postgres
    owner: postgres
    mode: 0700
    backup: yes
  when: postgres_s3

- name: Create Daily Cron job
  become: yes
  cron:
    name: "Backup postgres daily"
    job: "/usr/local/sbin/create_postgres_dump.sh daily {{ postgresql_backup_days }}"
    minute: 0
    hour: "{{ nadir_hour }}"
    weekday: "1,2,3,4,5,6"
    user: postgres
    cron_file: backup_postgres

- name: Create Weekly Cron job
  become: yes
  cron:
    name: "Backup postgres weekly"
    job: "/usr/local/sbin/create_postgres_dump.sh weekly {{ postgresql_backup_weeks * 7 }}"
    minute: 0
    hour: "{{ nadir_hour }}"
    weekday: 0
    user: postgres
    cron_file: backup_postgres

- name: copy retrieve script
  become: yes
  template:
    src: "plain/retrieve_backup.py.j2"
    dest: "/usr/local/sbin/retrieve_backup.py"
    group: root
    owner: root
    mode: 0700
    backup: yes
  when: postgres_s3

- name: copy restore script
  become: yes
  template:
    src: "plain/restore_from_backup.sh.j2"
    dest: "/usr/local/sbin/restore_from_backup.sh"
    group: root
    owner: root
    mode: 0700
    backup: yes
  when: postgres_s3
