---

- name: SharedDirHost
  hosts: shared_dir_host  # Should be one
  become: yes
  vars_files:
    - shared_dir/vars/main.yml
  tasks:
    - include: shared_dir/tasks/install.yml
    - include: shared_dir/tasks/setup_host.yml

- name: SharedDirClient
  hosts: webworkers:proxy:celery:pillowtop:shared_dir_host
  become: yes
  vars_files:
    - shared_dir/vars/main.yml
  tasks:
    - include: shared_dir/tasks/install.yml
    - include: shared_dir/tasks/setup_client.yml
