newrelic_java_agent_url: 'https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip'
newrelic_zip: "{{ www_home }}/newrelic.zip"
newrelic_dest: "{{ www_home }}/newrelic"
