---
- name: Install lvm tools
  sudo: yes
  apt: name=lvm2 state=present

- name: Check for valid partition table on block storage device
  sudo: yes
  shell: fdisk -l 2>&1 | grep 'Disk {{ item }} doesn.t contain a valid partition table'
  register: partition_check
  when: item is defined
  changed_when: false
  failed_when: false
  check_mode: no
  with_items: "{{ devices }}"

- name: Create partition on block storage volume
  sudo: yes
  shell: echo -e "o\nn\np\n1\n\n\nt\n1\n8e\nw" | fdisk {{ item.item }}
  # http://superuser.com/a/739586/86694
  # o  - clear in memory partition table
  # n  - new partition
  # p  - primary partition
  # 1  - partition number 1
  #    - default - start at beginning of disk 
  #    - default - use entire disk
  # t  - change type
  # 1  - select partition 1
  # 8e - lvm type
  # w  - write the partition table
  when: item is defined and item.rc == 0
  with_items: "{{ partition_check.results }}"

- name: Create volume group
  lvg:
    vg: consolidated
    pvs: '{{ partitions |join(",") }}'


- name: Create logical volume
  lvol:
    vg: consolidated
    lv: data1
    shrink: False
    size: 100%FREE

- name: Format block storage volume
  sudo: yes
  filesystem: fstype=ext4 dev={{ datavol_device }}1
  when: datavol_device is defined

- name: Mount block storage volume
  sudo: yes
  mount:
    name: "{{ encrypted_root }}"
    src: "{{ datavol_device }}1"
    fstype: ext4
    state: mounted
    opts: "defaults,noatime{{ datavol_opts | default('') | regex_replace('^(?=.)', ',') }}"
    dump: "0"
    passno: "0"
  when: datavol_device is defined
