---
- name: Create PostgreSQL databases on Worker
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    port: "{{ __postgresql_port }}"
    owner: "{{ item.user }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
  when: item.create and item.host in groups.citusdb_master
  with_items: "{{ postgresql_dbs.all }}"

- name: Add Citus Extension on Worker Database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: citus
    db: "{{ item.name }}"
    version: latest
  with_items: "{{ postgresql_dbs.all }}"
  when: item.host in groups.citusdb_master
