---
couchdb_port : 15984
couchdb_node_port : 15986
couchdb_dir: /usr/local/couchdb2/couchdb
couchdb_data_dir: '{{ encrypted_root }}/couchdb2'
couchdb_secure: False
couchdb_bind:
  ty: static
  host: '{{ inventory_hostname }}'
couchdb_socket_options: '[{recbuf, 262144}, {sndbuf, 262144}, {nodelay, true}]'

couchdb_install_parent_dir: /usr/local/couchdb2
couchdb_parent_srcs_dir: /usr/local/couchdb2/src

couchdb_init: 'sysv'

couchdb_compaction_settings:
  _default: '[{db_fragmentation, "10%"}, {view_fragmentation, "10%"}, {from, "17:00"}, {to, "22:30"}]'

couchdb_async_io_threads: 64

couchdb_require_valid_user: false
couchdb_require_valid_user_node_local: false
