- name: Install formplayer packages
  apt: name="{{ item }}" state=present
  become: yes
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: Create purging cron jobs
  become: yes
  cron:
    name: "{{ item.name }}"
    special_time: daily
    job: "/usr/sbin/tmpreaper {{ item.time_spec }} {{ item.dir }}"
    user: root
    cron_file: purge_formplayer_files
  with_items:
    - {name: 'Purge temp files', dir: '/tmp', time_spec: '2d'}
    - {name: 'Purge sqlite db files', dir: '{{ formplayer_data_dir }}', time_spec: '{{ formplayer_purge_time_spec }}'}

- name: Create cron job to archive sqlite db files
  become: yes
  cron:
    # should run every minute by default
    name: 'Archive sqlite db files'
    job: '{{ code_home }}/formplayer_build/current/scripts/archive_dbs.sh {{ formplayer_data_dir }} +{{ formplayer_archive_time_spec }}'
    user: '{{ cchq_user }}'
  when: formplayer_archive_time_spec is defined

- name: Formplayer build dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0755
  tags:
    - fp-localsettings
    - localsettings
  with_items:
    - "{{ formplayer_build_dir }}"
    - "{{ formplayer_data_dir }}"

- name: Copy Spring properties
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ formplayer_build_dir }}/{{ item.dest }}"
    group: cchq
    owner: cchq
    mode: 0644
  tags:
    - fp-localsettings
    - localsettings
  with_items:
    - {'src': 'application.properties.j2', 'dest': 'application.properties'}
    - {'src': 'sentry.properties.j2', 'dest': 'sentry.properties'}
