- name: "make sure the specified public interface actually exists"
  # a bit of a hack, but just hopefully prevents turning off access on all interfaces!
  shell: "ifconfig | grep {{ ufw_private_interface }}"
  changed_when: no

- name: allow incoming traffic on private interface
  ufw: rule=allow direction=in interface="{{ ufw_private_interface }}"

- name: default to denying all incoming traffic
  ufw: policy=deny direction=incoming

- name: turn on firewall
  ufw: state=enabled
