---

# Variables for role keepalived
keepalived_auth_pass: "1111"
keepalived_role: "MASTER"
keepalived_router_id: "52"
keepalived_shared_iface: "eth0"
keepalived_shared_ip: "192.168.1.1"
keepalived_check_process: "nginx"
keepalived_priority: "200"
keepalived_backup_priority: "100"
script_user: "root"
notify_script_path: "/etc/keepalived/notify_script"
keepalived_check_interval: 2
