# For a real deployment
# should be e.g. 'www.commcarehq.org'
SITE_HOST: '{{ groups.proxy.0 }}'
COMMTRACK_SITE_HOST: '{{ groups.proxy.0 }}'
NO_WWW_SITE_HOST: '{{ groups.proxy.0 }}'

# active sites defines the sites that will be configured with nginx
# "cchq" is always deployed, the corresponding configurations live in roles/nginx/vars
active_sites:
  cchq_redirect: True
  cchq_http: True
  cchq_http_redirect: True
  commtrack_ssl: True
  commtrack_http: True
  hq_status: False
  tableau: False
  icds_tableau: False
  dhis: False
  motech: False
  wiki: False


deploy_env: dev
fake_ssl_cert: yes

dev_users:
  present:
    - {name: droberts, group: dev, state: present, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcPH7f4OfZV8OEpISJiTxlIcx1J6HXjxG2END1t3RVgdAF6iYRBJYOnYzeAl1+bGMFZST9OrtWhiTQEy6L4fxgzOSYqmmvkvNbFMghiM41DUYIr9Gr9tlRpTDYg1WujlLLiq/TjpbatGapZzUjen992vpONGRWY7Qg1gVjjVM3Bb+kNB4UwK1IpJy0QJM9cOOeWbAEqov6nQdLirzyUtScrrF9P/B40tp6RcvNocC91z9x/5C4ovFduN+F8NClxoIvOf4vEp8BcG8CoiZeNHuYBkT8Nq2Tm/Zk/A5DJoIFs+pDf7Mw5G94s2/+YuKUZDDd9LjUufCBKijr9z+pnNTT droberts@dimagi.com'}
    - {name: tsheffels, group: dev, state: present, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhIPGGCiVuZ3bWRNOegBk6va/dL9er5pGfV0GspmlNzMBDZ3lrYXTs//fEAraUY/1wQo7/Qyy4kwvUDhHD2aoGrTB+Da+Bb7xGDfjLm1wGUqJWEcWvjHq7YnfGKu443gEJYaUDGryxuEdNwMFxps0xRSRLjkEQOcduEK+MC6D359bXA+FLUUPH+rerQ7RauuVkCzSc49Bk25BRpr/NM7uqX8wz16Ke7Sn4pSZAIrLnXPrxY9GuD+C7OGyG1w4So1r9QV7tR+NjsPapqrQQcHRtGlnjhzD+HoqD3SkG8ulTlVVyXbZVAtq0FjPRYwicdbs3cCEwsgGqHMLwHHCIxbox tyler.sheffels@gmail.com'}
  absent: []

# use this value to switch between nginx and apache
proxy_type: nginx

elasticsearch_endpoint: '{{ groups.elasticsearch.0 }}'
elasticsearch_memory: '128m'
elasticsearch_cluster_name: 'deves'

ECRYPTFS_PASSWORD: 'xxBvYiMZ3YVIVkFR'
KSPLICE_ACTIVE: no
KSPLICE_ACTIVATION_KEY:

NEW_RELIC_KEY:
run_newrelic_plugin_agent: False

DATADOG_ENABLED: False
DATADOG_API_KEY: null
DATADOG_APP_KEY: null

CLOUDANT_CLUSTER_NAME: null

AMQP_USER: "{{ deploy_env }}_worker"
AMQP_PASSWORD: '******'
AMQP_HOST: "{{ groups.celery.0 }}"
AMQP_NAME: commcarehq

# This dumps the dummy keystore, but allows the ansible script to continue, should be overriden for real deploys
keystore_file: 'DimagiKeyStore'

postgres_users:
  commcare:
    username: "{{ localsettings.PG_DATABASE_USER }}"
    password: "{{ localsettings.PG_DATABASE_PASSWORD }}"

postgres_config:
  max_connections: 20
  pgb_max_connections: 100
  pgb_default_pool: 15
  pgb_reserve_pool: 4
  pgb_pool_timeout: 2
  pgb_pool_mode: session

supervisor_http_enabled: True
supervisor_http_username: user
supervisor_http_password: 123

localsettings:
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
    - "{{ SITE_HOST }}"
  ANALYTICS_API_ID_PUBLIC_COMMCARE: ''
#  BANK_ACCOUNT_NUMBER:
#  BANK_ADDRESS:
#  BANK_NAME:
#  BANK_ROUTING_NUMBER:
#  BANK_SWIFT_CODE:
  BANK_ROUTING_NUMBER_ACH: ''
  BANK_ROUTING_NUMBER_WIRE: ''
  BITLY_APIKEY: ''
  BITLY_LOGIN: ''
#  BOOKKEEPER_CONTACT_EMAILS:
  BROKER_URL: 'amqp://{{ AMQP_USER }}:{{ AMQP_PASSWORD }}@{{ AMQP_HOST }}:5672/{{ AMQP_NAME }}'
  CELERY_FLOWER_URL: "http://{{ groups.celery.0 }}:5555"
  CELERY_PERIODIC_QUEUE: 'celery_periodic'
#  CELERY_REMINDER_CASE_UPDATE_QUEUE:
#  CELERY_REMINDER_RULE_QUEUE:
  CELERY_RESULT_BACKEND: 'database'
#  COUCHPULSE_DATABASE_URL:
#  COUCH_CACHE_DOCS:
#  COUCH_CACHE_VIEWS:
  COUCH_DATABASE_NAME: commcarehq
  COUCH_HTTPS: no
  COUCH_PASSWORD: commcarehq
  COUCH_SERVER_ROOT: "{{ groups.couchdb.0 }}:5984"
  COUCH_USERNAME: commcarehq
  CTABLE_PREFIX: null
  DEFAULT_CACHE: redis
  DEPLOY_MACHINE_NAME: "{{ inventory_hostname }}"
  DROPBOX_APP_NAME: ''
  DROPBOX_KEY: ''
  DROPBOX_SECRET: ''
  ELASTICSEARCH_HOST: "{{ groups.elasticsearch.0 }}"
  ELASTICSEARCH_PORT: '9200'
  EMAIL_LOGIN: ''
  EMAIL_PASSWORD: ''
  # Run `python -m smtpd -n -c DebuggingServer 0.0.0.0:1025` on proxy
  EMAIL_SMTP_HOST: '{{ groups.proxy.0 }}'
  EMAIL_SMTP_PORT: '1025'
  # use True in prod!
  EMAIL_USE_TLS: no
#  ES_CASE_CHECK_DIRECT_DOC_ID:
#  ES_QUERY_CHUNKSIZE:
#  ES_XFORM_CHECK_DIRECT_DOC_ID:
  GMAPS_API_KEY: ''
  GOOGLE_ANALYTICS_API_ID: ''
  HUBSPOT_API_ID: ''
  HUBSPOT_API_KEY: ''
  HQ_INSTANCE: 'dev'
#  INVOICE_FROM_ADDRESS:
#  INVOICE_PREFIX:
#  INVOICE_STARTING_NUMBER:
  JAR_KEY_ALIAS: ''
  JAR_KEY_PASS: ''
  JAR_STORE_PASS: ''
  KAFKA_URL: ''
  KISSMETRICS_KEY: ''
#  MAILCHIMP_APIKEY:
#  MAILCHIMP_COMMCARE_USERS_ID:
#  MAILCHIMP_MASS_EMAIL_ID:
#  MANDRILL_APIKEY:
#  MAPS_LAYERS:
#  MEDIA_ROOT:
  OPEN_EXCHANGE_RATES_API_ID:
  PG_DATABASE_HOST: "{{ groups.postgresql.0 }}"
  PG_DATABASE_NAME: commcarehq
  PG_DATABASE_PASSWORD: commcarehq
  PG_DATABASE_USER: commcarehq
#  PILLOWTOP_MACHINE_ID:
#  PILLOW_RETRY_QUEUE_ENABLED:
#  PRODUCTION_COUCHDB_URI:
  REDIS_DB: '0'
  REDIS_HOST: "{{ groups.redis.0 }}"
  REDIS_PORT: '6379'
#  REMINDERS_QUEUE_ENABLED:
  REPORT_DATABASE_NAME: commcarehq_reporting
  UCR_DATABASE_NAME: commcarehq_ucr
  REPORT_OBJECT_OWNER: null
  SECRET_KEY: "JHX1y7iG0bQaVICcBXrQYw1fcJcomC24p6lxAfKMG0B5g7D5"
  SEGMENT_ANALYTICS_KEY: ''
#  SIMPLE_API_KEYS:
#  SMS_QUEUE_ENABLED: ''
#  STAGING_DOMAINS:
#  STATIC_ROOT:
#  STRIPE_PRIVATE_KEY:
#  STRIPE_PUBLIC_KEY:
  TOUCHFORMS_API_PASSWORD: 'TsyasEivKf4GtbQX'
  TOUCHFORMS_API_USER: 'touchforms@example.com'
  XFORMS_PLAYER_URL: "http://{{ groups.touchforms.0 }}:4444"
