# For a real deployment
# should be e.g. 'www.commcarehq.org'
SITE_HOST: 192.168.33.17

settings:
  ECRYPTFS_PASSWORD: 'xxBvYiMZ3YVIVkFR'
  KSPLICE_ACTIVE: no
  KSPLICE_ACTIVATION_KEY:

AMQP_USER: hq_worker
AMQP_PASSWORD: '******'
AMQP_HOST: "{{ groups.celery.0 }}"
AMQP_NAME: commcarehq

localsettings:
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
    - "{{ SITE_HOST }}"
#  BANK_ACCOUNT_NUMBER:
#  BANK_ADDRESS:
#  BANK_NAME:
#  BANK_ROUTING_NUMBER:
#  BANK_SWIFT_CODE:
  BITLY_APIKEY: ''
  BITLY_LOGIN: ''
#  BOOKKEEPER_CONTACT_EMAILS:
#  BROKER_URL: 'amqp://{{ AMQP_USER }}:{{ AMQP_PASSWORD }}@{{ AMQP_HOST }}:5672/{{ AMQP_NAME }}'
  BROKER_URL: ''
  CELERY_FLOWER_URL: "http://{{ groups.celery.0 }}:5555"
  CELERY_PERIODIC_QUEUE: 'celery_periodic'
#  CELERY_REMINDER_CASE_UPDATE_QUEUE:
#  CELERY_REMINDER_RULE_QUEUE:
  CELERY_RESULT_BACKEND: 'database'
#  COUCHPULSE_DATABASE_URL:
#  COUCH_CACHE_DOCS:
#  COUCH_CACHE_VIEWS:
  COUCH_DATABASE_NAME: commcarehq
  COUCH_HTTPS: no
  COUCH_PASSWORD: commcarehq
  COUCH_SERVER_ROOT: "{{ groups.couchdb.0 }}:5984"
  COUCH_USERNAME: commcarehq
  CTABLE_PREFIX: null
  DEPLOY_MACHINE_NAME: "{{ inventory_hostname }}"
#  DOMAIN_SYNC_DATABASE_NAME:
  ELASTICSEARCH_HOST: "{{ groups.elasticsearch.0 }}"
  ELASTICSEARCH_PORT: '9200'
  EMAIL_LOGIN: 'notifications@dimagi.com'
  EMAIL_PASSWORD: '******'
  EMAIL_SMTP_HOST: 'smtp.gmail.com'
  EMAIL_SMTP_PORT: '587'
#  ES_CASE_CHECK_DIRECT_DOC_ID:
#  ES_QUERY_CHUNKSIZE:
#  ES_XFORM_CHECK_DIRECT_DOC_ID:
  GMAPS_API_KEY: ''
  GOOGLE_ANALYTICS_ID: ''
#  INVOICE_FROM_ADDRESS:
#  INVOICE_PREFIX:
#  INVOICE_STARTING_NUMBER:
  JAR_KEY_ALIAS: ''
  JAR_KEY_PASS: ''
  JAR_STORE_PASS: ''
#  KAFKA_HOST:
  MACH_PASSWORD: ''
  MACH_USERNAME: ''
#  MAILCHIMP_APIKEY:
#  MAILCHIMP_COMMCARE_USERS_ID:
#  MAILCHIMP_MASS_EMAIL_ID:
#  MANDRILL_APIKEY:
#  MAPS_LAYERS:
#  MEDIA_ROOT:
  MEMCACHED_HOST: "{{ groups.memcached.0 }}"
  MEMCACHED_PORT: '11211'
  OPEN_EXCHANGE_RATES_ID:
  PG_DATABASE_HOST: "{{ groups.postgresql.0 }}"
  PG_DATABASE_NAME: commcarehq
  PG_DATABASE_PASSWORD: commcarehq
  PG_DATABASE_USER: commcarehq
#  PILLOWTOP_MACHINE_ID:
#  PILLOW_RETRY_QUEUE_ENABLED:
  PINGDOM_ID: ''
#  PRODUCTION_COUCHDB_URI:
  REDIS_DB: '0'
  REDIS_HOST: "{{ groups.redis.0 }}"
  REDIS_PORT: '6379'
#  REMINDERS_QUEUE_ENABLED:
  REPORT_DATABASE_NAME: commcarehq_reporting
  REPORT_OBJECT_OWNER: null
  SECRET_KEY: "JHX1y7iG0bQaVICcBXrQYw1fcJcomC24p6lxAfKMG0B5g7D5"
#  SENTRY_DSN:
#  SIMPLE_API_KEYS:
  SMS_GATEWAY_PARAMS:
  SMS_GATEWAY_URL: ''
#  SMS_QUEUE_ENABLED: ''
#  STAGING_DOMAINS:
#  STATIC_ROOT:
#  STRIPE_PRIVATE_KEY:
#  STRIPE_PUBLIC_KEY:
  TOUCHFORMS_API_PASSWORD: 'TsyasEivKf4GtbQX'
  TOUCHFORMS_API_USER: 'touchforms@example.com'
  UNICEL_PASSWORD: ''
  UNICEL_RECEIVE_PHONE: ''
  UNICEL_SENDER: ''
  UNICEL_USERNAME: ''
  XFORMS_PLAYER_URL: "http://{{ groups.touchforms.0 }}:4444"
