# variables used in conf files

# the following are defined in group_vars/all.yml
#riak_data_dir: ...
#riak_port: ...
#riakcs_port: ...
#stanchion_data_dir: ...
#stanchion_port: ...

riak_data_root_leveldb: "{{ riak_data_dir }}/leveldb"
riak_data_root_blocks: "{{ riak_data_dir }}/blocks"
riak_ring_dir: "{{ riak_data_dir }}/ring"
riak_nodename: "riak-{{ inventory_hostname_short }}@{{ inventory_hostname }}"
riak_ring_size: 128

riakcs_ebin: /usr/lib/riak-cs/lib/riak_cs-{{ riakcs_version }}/ebin
