---

galaxy_name: weareinteractive.apt
github_user: weareinteractive
github_name: ansible-apt
badges: |
  [![Build Status](https://img.shields.io/travis/weareinteractive/ansible-apt.svg)](https://travis-ci.org/weareinteractive/ansible-apt)
  [![Galaxy](http://img.shields.io/badge/galaxy-weareinteractive.apt-blue.svg)](https://galaxy.ansible.com/weareinteractive/apt)
  [![GitHub Tags](https://img.shields.io/github/tag/weareinteractive/ansible-apt.svg)](https://github.com/weareinteractive/ansible-apt)
  [![GitHub Stars](https://img.shields.io/github/stars/weareinteractive/ansible-apt.svg)](https://github.com/weareinteractive/ansible-apt)
description: |
  > * updates apt
  > * cleans up apt
  > * configures apt
  > * installs packages
  > * add repositories
  > * add keys
  > * manages unattended upgrades
  > * optionally alters solution cost
  > * optionally allows filesystems to be remounted

  **Note:**

  > Since Ansible Galaxy supports [organization](https://www.ansible.com/blog/ansible-galaxy-2-release) now, this role has moved from `franklinkim.apt` to `weareinteractive.apt`!
