- name: Touchforms user (cleanup)
  delegate_to: "{{ groups.webworkers.0 }}"
  become: yes
  become_user: "{{ cchq_user }}"
  vars:
    ansible_ssh_pipelining: true
  django_user:
    app_path: "{{ code_home }}"
    virtualenv: "{{ virtualenv_home }}"
    state: absent
    name: "{{ localsettings.TOUCHFORMS_API_USER }}"
    password: "{{ localsettings.TOUCHFORMS_API_PASSWORD }}"
    superuser: yes
  when: not touchforms_enabled

- name: Copy Jython localsettings.py (cleanup)
  become: yes
  file:
    dest: "{{ code_home }}/submodules/touchforms-src/touchforms/backend/localsettings.py"
    state: absent
  tags:
    - tf-localsettings
    - localsettings
  when: not touchforms_enabled or 'touchforms' not in group_names

- name: create touchforms data directory (cleanup)
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    state: absent
  with_items:
    - "{{ touchforms_data_dir }}"
  when: not touchforms_enabled or 'touchforms' not in group_names

- name: Create session purging cron job (cleanup)
  become: yes
  cron:
    name: "Purge old touchforms sessions"
    special_time: daily
    job: "find {{ touchforms_data_dir }} -maxdepth 1 -mtime +90 -delete"
    user: root
    cron_file: ../crontab
  when: not touchforms_enabled or 'touchforms' not in group_names
