- name: create required igor directories
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ igor_dir }}"
    - "{{ igor_log_dir }}"
    - "{{ igor_src_dir }}"
  tags:
    - igor

- name: Pull full Igor source
  git:
    repo: "{{ igor_repository }}"
    dest: "{{ igor_src_dir }}"
    recursive: yes
    accept_hostkey: yes
    update: yes
  sudo_user: "{{ cchq_user }}"
  tags:
    - igor

- name: Set igor supervisor confs
  sudo_user: "{{ cchq_user }}"
  template:
    src: "supervisor/{{ item }}.conf.j2"
    dest: "{{ supervisor_task_conf }}/{{ item }}.conf"
  with_items:
    - "igor"
  tags:
    - igor
