---
- name: Add mosh apt repo
  apt_repository: repo='ppa:keithw/mosh' state=present
  register: add_mosh_repo

- name: Add git apt repo
  apt_repository: repo='ppa:git-core/ppa' state=present
  register: add_git_repo

# http://stackoverflow.com/a/16303380/835696
- name: Add git nodejs repo
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  register: add_nodejs_repo

- name: Add gradle repo
  apt_repository: repo='ppa:cwchien/gradle' state=present
  register: add_gradle_repo

- name: Add PostreSQL apt repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main' state=present
  register: add_postgres_repo

- name: Add PosgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update package list
  apt: update_cache=yes
  when: add_nodejs_repo|changed or add_mosh_repo|changed or add_git_repo|changed or add_postgres_repo|changed or add_gradle_repo|changed

# Install base packages, common to all servers
- name: Install common packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-client-common
    - postgresql-client-{{ postgresql_version }}
    - libxml2-dev
    - libxslt1-dev
    - git
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils
    - ntp
    - nodejs
    - at
    - screen
    - gettext
    - python-software-properties
    - mosh
    - libjpeg-dev
    - libfreetype6-dev
    - gradle
    - ranger  # cmdline file browser
    - libffi-dev  # Required for installing github3py
    - libssl-dev  # Required for pip setup tools
    - tmux
    - unzip

- name: Set NPM registry
  command: 'npm config set registry http://registry.npmjs.org/'
  sudo: yes

- name: Install npm items
  npm: name={{ item }} state=present global=yes
  sudo: yes
  with_items:
    - npm@3.6.0
    - less@1.3.1
    - n@1.3.0
    - bower@1.5.3
    - uglify-js@2.6.1

- name: Update Node
  command: 'n 0.10.29'
  sudo: yes

- stat: path=/opt/lessc
  register: lessc_stat

- name: Install lessc from source
  sudo: yes
  # this is lessc 1.7.3
  git: repo='https://github.com/less/less.js.git' dest='/opt/lessc' version='546bedd' recursive=yes accept_hostkey=yes
  when: not lessc_stat.stat.exists

- name: Install pip packages
  pip: name={{ item }}
  sudo: yes
  with_items:
    - virtualenv
    - sh
    - httplib2

- name: Install virtualenv-clone
  sudo: yes
  pip:
    name: virtualenv-clone
    version: 0.2.6
