---
- name: Add mosh apt repo
  apt_repository: repo='ppa:keithw/mosh' state=present
  register: add_mosh_repo

- name: Add git apt repo
  apt_repository: repo='ppa:git-core/ppa' state=present
  register: add_git_repo

# http://stackoverflow.com/a/16303380/835696
- name: Add git nodejs repo
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  register: add_nodejs_repo

- name: Update package list
  apt: update_cache=yes
  when: add_nodejs_repo|changed or add_mosh_repo|changed or add_git_repo|changed

# Install base packages, common to all servers
- name: Install common packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-client-common
    - postgresql-client-{{ postgresql_version }}
    - libxml2-dev
    - libxslt1-dev
    - git
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils
    - ntp
    - nodejs
    - at
    - screen
    - gettext
    - python-software-properties
    - mosh
    - libjpeg-dev

- name: Set NPM registry
  command: 'npm config set registry http://registry.npmjs.org/'
  sudo: yes

- name: Install npm lessc
  npm: name={{ item }} state=present global=yes
  sudo: yes
  with_items:
    - less@1.3.1
    - n@1.3.0
    - bower@1.5.3

- name: Update Node
  command: 'n 0.10.29'
  sudo: yes

- name: Install lessc from source
  sudo: yes
  # this is lessc 1.7.3
  git: repo='https://github.com/less/less.js' dest='/opt/lessc' version='546bedd' recursive=yes accept_hostkey=yes depth=1

- name: Install pip packages
  pip: name={{ item }}
  sudo: yes
  with_items:
    - fabric
    - virtualenv
    - sh

- name: Install virtualenv-clone
  sudo: yes
  pip:
    name: virtualenv-clone
    version: 0.2.6
