- name: define formplayer spring services
  become: cchq
  template:
    src: "../templates/supervisor_formplayer_spring.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_formplayer_spring.conf"
  with_items:
    - env_vars:
        http_proxy: "{% if http_proxy_address is defined %}http://{{ http_proxy_address }}:{{ http_proxy_port }}{% endif %}"
        https_proxy: "{% if http_proxy_address is defined %}https://{{ http_proxy_address }}:{{ http_proxy_port }}{% endif %}"
        no_proxy: "{% if http_proxy_address is defined %}{{ groups['all'] | join(',') }},{{ app_processes_config.additional_no_proxy_hosts }}{% endif %}"
        TMPDIR: '{{ encrypted_tmp }}'
  tags:
    - services
  register: formplayer_files

- set_fact:
    formplayer_supervisor_files: "{{ formplayer_files.get('results', []) }}"
  tags:
    - services

- set_fact:
    formplayer_managed_files: "{{ formplayer_supervisor_files|selectattr('dest', 'string')|map(attribute='dest')|list }}"
  tags:
    - services
