- name: define touchforms services
  become: cchq
  template:
    src: "../templates/supervisor_formsplayer.conf.j2"
    dest: "{{ service_home }}/{{ deploy_env }}_supervisor_formsplayer.conf"
  tags:
    - services
  register: touchforms_files

- set_fact:
    touchforms_supervisor_files: "{{ touchforms_files.get('results', []) }}"

- set_fact:
    touchforms_managed_files: "{{ touchforms_supervisor_files|selectattr('dest', 'string')|map(attribute='dest')|list }}"
