SITE_HOST: 'staging.commcarehq.org'
NO_WWW_SITE_HOST: 'staging.commcarehq.org'
COMMTRACK_SITE_HOST: 'test.commtrack.org'
J2ME_SITE_HOST: 'j2mestaging.commcarehq.org'
deploy_env: staging

active_sites:
  cchq_redirect: True
  cchq_http: True
  cchq_http_redirect: True
  cchq_http_j2me: True
  commtrack_ssl: False
  commtrack_http: False
  hq_status: False
  tableau: False
  icds_tableau: False
  dhis: False
  wiki: False
  motech: False
  motech1: False
  motech2: False
  riakcs: True
  riak: True
  riak_http: True

proxy_type: nginx

primary_ssl_env: "staging"

ansible_user_password_sha_512: "{{ secrets.ANSIBLE_USER_PASSWORD_SHA_512 }}"
fake_ssl_cert: no

NEW_RELIC_KEY: "{{ secrets.NEW_RELIC_KEY }}"
run_newrelic_plugin_agent: False

DATADOG_ENABLED: False

elasticsearch_endpoint: '{{ groups.elasticsearch.0 }}'
elasticsearch_cluster_name: 'staginges'

# Source paths of certs
apache2_key_file: '../config/{{ deploy_env }}/ssl/commcarehq.org.key'
apache2_ca_file: '../config/{{ deploy_env }}/ssl/hq_thawtecabundle.crt'
apache2_cert_file: '../config/{{ deploy_env }}/ssl/commcarehq.org.crt'
# Nginx only accepts on cert, so cat the site cert and chain:
# $ cat commcarehq.org.crt hq_thawtecabundle.crt > commcarehq.org.combined.crt
nginx_combined_cert_file: '../config/{{ deploy_env }}/ssl/commcarehq.org.combined.crt'

# Commtrack Certs
commtrack_nginx_combined_cert_file: '../config/{{ deploy_env }}/ssl/commtrack.org.combined.crt'
commtrack_key_file: '../config/{{ deploy_env }}/ssl/commtrack.org.key'

supervisor_http_enabled: True
supervisor_http_username: "{{ secrets.SUPERVISOR_HTTP_USERNAME }}"
supervisor_http_password: "{{ secrets.SUPERVISOR_HTTP_PASSWORD }}"

keystore_file: '../config/DimagiKeyStore'

backup_blobdb: False
backup_postgres: False
backup_es: False
postgres_s3: False

postgres_users: "{{ secrets.POSTGRES_USERS }}"

postgres_config:
  max_connections: 20
  pgb_max_connections: 100
  pgb_default_pool: 15
  pgb_reserve_pool: 4
  pgb_pool_timeout: 2
  pgb_pool_mode: transaction

formplayer_db_name: formplayer

postgresql_dbs:
  - django_alias: default
    name: "{{localsettings.PG_DATABASE_NAME}}"
  - django_alias: proxy
    name: commcarehq_proxy
  - django_alias: p1
    name: commcarehq_p1
    shards: [0, 99]
  - django_alias: p2
    name: commcarehq_p2
    shards: [100, 199]
  - django_alias: p3
    name: commcarehq_p3
    shards: [200, 299]
  - django_alias: p4
    name: commcarehq_p4
    shards: [300, 399]
  - django_alias: p5
    name: commcarehq_p5
    shards: [400, 511]
  - name: "{{localsettings.UCR_DATABASE_NAME}}"
  - name: "{{ formplayer_db_name }}"

ECRYPTFS_PASSWORD: "{{ secrets.ECRYPTFS_PASSWORD }}"

KSPLICE_ACTIVE: yes
KSPLICE_ACTIVATION_KEY: "{{ secrets.KSPLICE_ACTIVATION_KEY }}"

AMQP_USER: "{{ secrets.AMQP_USER }}"
AMQP_PASSWORD: "{{ secrets.AMQP_PASSWORD }}"
AMQP_HOST: "{{ groups.rabbitmq.0 }}"
AMQP_NAME: commcarehq

ufw_private_interface: eth1

etc_host_lines:

localsettings:
  ALLOWED_HOSTS:
    - staging.commcarehq.org
    - j2mestaging.commcarehq.org
    - localhost
    - 127.0.0.1
    - testserver
  BANK_ACCOUNT_NUMBER: "{{ localsettings_private.BANK_ACCOUNT_NUMBER }}"
  BANK_ADDRESS: { 'first_line': "1 Citizens Drive", 'city': "Riverside", 'region': "RI", 'postal_code': "02915" }
  BANK_NAME: "RBS Citizens N.A."
  BANK_SWIFT_CODE: 'CTZIUS33'
  BANK_ROUTING_NUMBER_ACH: "{{ localsettings_private.BANK_ROUTING_NUMBER_ACH }}"
  BANK_ROUTING_NUMBER_WIRE: "{{ localsettings_private.BANK_ROUTING_NUMBER_WIRE }}"
  BITLY_APIKEY: "{{ localsettings_private.BITLY_APIKEY }}"
  BITLY_LOGIN: "{{ localsettings_private.BITLY_LOGIN }}"
  BOOKKEEPER_CONTACT_EMAILS: "{{ localsettings_private.BOOKKEEPER_CONTACT_EMAILS }}"
  BROKER_URL: 'amqp://{{ secrets.AMQP_USER }}:{{ secrets.AMQP_PASSWORD }}@{{ AMQP_HOST }}:5672/{{ AMQP_NAME }}'
  CELERY_FLOWER_URL: "http://{{ groups.celery.0 }}:5555"
  CELERY_PERIODIC_QUEUE: 'celery_null'
  CELERY_REMINDER_CASE_UPDATE_QUEUE:
  CELERY_REMINDER_RULE_QUEUE:
  CELERY_RESULT_BACKEND: 'djcelery.backends.database:DatabaseBackend'
  COUCH_CACHE_DOCS: True
  COUCH_CACHE_VIEWS: True
  COUCH_DATABASE_NAME: "{{ localsettings_private.COUCH_DATABASE_NAME }}"
  COUCH_HTTPS: yes
  COUCH_PASSWORD: "{{ localsettings_private.COUCH_PASSWORD }}"
  COUCH_SERVER_ROOT: "commcarehq.cloudant.com"
  COUCH_USERNAME: "{{ localsettings_private.COUCH_USERNAME }}"
  COUCH_PORT: 443
  DEPLOY_MACHINE_NAME: "{{ ansible_hostname }}"
  DROPBOX_APP_NAME: 'CommCareHQFiles - Staging'
  DROPBOX_KEY: "{{ localsettings_private.DROPBOX_KEY }}"
  DROPBOX_SECRET: "{{ localsettings_private.DROPBOX_SECRET }}"
  ELASTICSEARCH_HOST: "{{ groups.elasticsearch.0 }}"
  ELASTICSEARCH_PORT: '9200'
  EMAIL_LOGIN: "{{ localsettings_private.EMAIL_LOGIN }}"
  EMAIL_PASSWORD: "{{ localsettings_private.EMAIL_PASSWORD }}"
  EMAIL_SMTP_HOST: email-smtp.us-east-1.amazonaws.com
  EMAIL_SMTP_PORT: 587
  EMAIL_USE_TLS: yes
  FORMPLAYER_URL: "/formplayer"
  GMAPS_API_KEY: "{{ localsettings_private.GMAPS_API_KEY }}"
  GOOGLE_ANALYTICS_API_ID: "{{ localsettings_private.GOOGLE_ANALYTICS_API_ID }}"
  HQ_INSTANCE: 'staging'
  HUBSPOT_API_ID: "{{ localsettings_private.HUBSPOT_API_ID }}"
  HUBSPOT_API_KEY: "{{ localsettings_private.HUBSPOT_API_KEY }}"
  INVOICE_FROM_ADDRESS:
    'name': "Dimagi, Inc."
    'first_line': "585 Massachusetts Ave"
    'city': "Cambridge"
    'region': "MA"
    'postal_code': "02139"
    'country': "US"
    'phone_number': "(617) 649-2214"
    'email': "accounts@dimagi.com"
    'website': "http://www.dimagi.com"
  INVOICE_PREFIX: INC-
  INVOICE_STARTING_NUMBER: 5000
  JAR_KEY_ALIAS: javarosakey
  JAR_KEY_PASS: "{{ localsettings_private.JAR_KEY_PASS }}"
  JAR_STORE_PASS: "{{ localsettings_private.JAR_STORE_PASS }}"
  J2ME_ADDRESS: "{{ J2ME_SITE_HOST }}"
  KAFKA_URL: "{{ groups.kafka.0 }}:9092"
  KISSMETRICS_KEY: "{{ localsettings_private.KISSMETRICS_KEY }}"
  MAPS_LAYERS: "{{ localsettings_private.MAPS_LAYERS }}"
  MIA_THE_DEPLOY_BOT_API: "{{ localsettings_private.MIA_THE_DEPLOY_BOT_API }}"
  OPEN_EXCHANGE_RATES_API_ID: "{{ localsettings_private.OPEN_EXCHANGE_RATES_API_ID }}"
  PG_DATABASE_HOST: "{{ groups.postgresql.0 }}"
  PG_DATABASE_NAME: commcarehq
  PG_DATABASE_PASSWORD: "{{ secrets.POSTGRES_USERS.commcare.password }}"
  PG_DATABASE_USER: "{{ secrets.POSTGRES_USERS.commcare.username }}"
  PG_DATABASE_PORT: 6432
  PILLOWTOP_MACHINE_ID: staging-hqdb0-ubuntu
  PILLOW_RETRY_QUEUE_ENABLED: True
  REDIS_DB: '0'
  REDIS_HOST: "{{ groups.redis.0 }}"
  REDIS_PORT: '6379'
  REMINDERS_QUEUE_ENABLED: False
  AMAZON_S3_ACCESS_KEY: "{{ localsettings_private.AMAZON_S3_ACCESS_KEY }}"
  AMAZON_S3_SECRET_KEY: "{{ localsettings_private.AMAZON_S3_SECRET_KEY }}"
  SECRET_KEY: "{{ localsettings_private.SECRET_KEY }}"
  SIMPLE_API_KEYS:
  SMS_GATEWAY_PARAMS: "{{ localsettings_private.SMS_GATEWAY_PARAMS }}"
  SMS_GATEWAY_URL: 'http://gw1.promessaging.com/sms.php'
  SMS_QUEUE_ENABLED: False
  STATIC_ROOT:
  STATIC_CDN: 'https://d2f60qxn5rwjxl.cloudfront.net'
  STRIPE_PRIVATE_KEY: "{{ localsettings_private.STRIPE_PRIVATE_KEY }}"
  STRIPE_PUBLIC_KEY: "{{ localsettings_private.STRIPE_PUBLIC_KEY }}"
  TOUCHFORMS_API_PASSWORD: "{{ localsettings_private.TOUCHFORMS_API_PASSWORD }}"
  TOUCHFORMS_API_USER: "{{ localsettings_private.TOUCHFORMS_API_USER }}"
  UCR_DATABASE_NAME: commcarehq_ucr
  USE_PARTITIONED_DATABASE: True
  WS4REDIS_CONNECTION_HOST: "{{ groups.redis.0 }}"
  XFORMS_PLAYER_URL: "http://{{ groups.touchforms.0 }}:4444/"
