---
- name: Restart postgres
  become: yes
  action: service name=postgresql state=restarted

- name: Reload postgres
  become: yes
  action: service name=postgresql state=reloaded

- name: Start pgbouncer
  become: yes
  action: service name=pgbouncer state=started

- name: Reload pgbouncer
  become: yes
  action: service name=pgbouncer state=reloaded

- name: Run ldconfig
  become: yes
  action: command ldconfig
