- name: Download Java New Relic Agent
  get_url:
    url: '{{ newrelic_java_agent_url }}'
    dest: '{{ newrelic_zip }}'

- name: Unzip agent
  unarchive:
    src: '{{ newrelic_zip }}'
    dest: '{{ newrelic_dest }}'
    copy: no
    owner: '{{ cchq_user }}'
    group: '{{ cchq_user }}'

- name: Copy newrelic template
  sudo_user: "{{ cchq_user }}"
  template:
    src: newrelic.yml.j2
    dest: '{{ newrelic_dest }}/newrelic/newrelic.yml'
