---
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_commcare"
   listen: "443 ssl{{ ' default_server' if deploy_env == primary_ssl_env else '' }}"
   server_name: "{{ SITE_HOST }}"
   client_max_body_size: 100m
   use_balancer: True
   proxy_set_headers:
   - "Host $http_host"
   - "X-Forwarded-For $remote_addr"
   add_header: "X-Frame-Options DENY"
   error_page: "502 503 /errors/50x.html"
   access_log: "{{ log_home }}/{{ deploy_env }}-timing.log timing"
   location1:
    name: /
    use_balancer: True
    proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
    proxy_next_upstream_tries: 1
    proxy_read_timeout: 900s
   location2:
    name: "/static"
    alias: "{{ nginx_static_home }}"
    try_files: "$uri $uri/index.html $uri/ =404"
   location3:
    name: "/{{ transfer_payload_dir_name }}"
    alias: "{{ transfer_payload_dir }}"
    is_internal: True
   location4:
    name: /errors
    alias: "{{ errors_home }}/pages"
   location5:
    name: /ws
    proxy_pass: "http://unix:{{ www_home }}/web.socket"
    proxy_http_version: "1.1"
	proxy_set_header: "Upgrade $http_upgrade"
    proxy_set_header: "Connection \"upgrade\""
