---
nginx_ssl_cert: "{{ commtrack_nginx_ssl_cert }}"
nginx_ssl_key:  "{{ commtrack_nginx_ssl_key}}"

nginx_sites:
- server:
   file_name: zz_commtrack #There was a bug where a phone would default to connecting to commtrack on login and use this cert, then failing.  Renaming the file makes it load later and work.
   listen: "443 ssl"
   server_name: "{{ COMMTRACK_SITE_HOST }} www.{{ COMMTRACK_SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       return: "301 https://{{ SITE_HOST }}$request_uri"
     - name: /home
       return: "302 https://{{ SITE_HOST }}/solutions/#supply"
     - name: "= /"
       return: "302 https://{{ SITE_HOST }}/solutions/#supply"
