---
nginx_sites:
- server:
   file_name: commtrack_public
   listen: "80"
   server_name: "{{ COMMTRACK_SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       return: "301 https://{{ SITE_HOST }}$request_uri"
     - name: /home
       return: "302 https://{{ SITE_HOST }}/solutions/#supply"
     - name: " = /"
       return: "302 https://{{ SITE_HOST }}/solutions/#supply"
