---
nginx_ssl_cert: {{ commtrack_nginx_ssl_cert }}
nginx_ssl_key:  {{ commtrack_nginx_ssl_key}}

nginx_sites:
- server:
   file_name: commtrack
   listen: "443 ssl"
   server_name: "{{ COMMTRACK_SITE_HOST }}"
   client_max_body_size: 100m
   use_balancer: True
   proxy_set_header: "Host $http_host"
   location1:
    name: /
    return: "301 https://{{ SITE_HOST }}$request_uri"
