---
# Send anything from http -> https
nginx_sites:
- server:
   file_name: "motech2_http"
   listen: "80"
   server_name: "test-supply-motech.commcarehq.org"
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       return: "301 https://$server_name$request_uri"
