---
# Send anything from http -> https
nginx_sites:
- server:
   file_name: "wiki_http"
   listen: "80"
   server_name: "wiki.commcarehq.org help.commcarehq.org"
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       return: "301 https://$server_name/display/commcarepublic/Home"
