---
nginx_sites:
- server:
   file_name: wiki
   listen: "443 ssl"
   server_name: "wiki.commcarehq.org help.commcarehq.org"
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       proxy_pass: https://confluence.internal.dimagi.com
     - name: "= /"
       return: "302 https://$server_name/display/commcarepublic/Home"
     - name: /errors
       alias: "{{ errors_home }}/pages"
