image: linuturk/ubuntu-ansible
env:
  - RAXUSER={{rax_user}}
  - RAXKEY={{rax_key}}
script:
  - rsyslogd &
  - ansible-galaxy install -r $DRONE_BUILD_DIR/tests/roles.list
  - ansible-playbook --syntax-check $DRONE_BUILD_DIR/tests/main.yml
  - ansible-playbook $DRONE_BUILD_DIR/tests/main.yml --extra-vars "rackspace_username=$RAXUSER rackspace_apikey=$RAXKEY"
  - ansible-playbook $DRONE_BUILD_DIR/tests/main.yml --extra-vars "rackspace_username=$RAXUSER rackspace_apikey=$RAXKEY"
  - "ansible-playbook $DRONE_BUILD_DIR/tests/main.yml --extra-vars \"rackspace_username=$RAXUSER rackspace_apikey=$RAXKEY\" | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
