---
- name: Create directories for certificates
  become: yes
  file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - "{{ ssl_certs_dir }}"
    - "{{ ssl_keys_dir }}"

- name: Link CCHQ SSL cert
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{SITE_HOST}}/fullchain.pem"
    dest: "{{ ssl_certs_dir }}/{{ nginx_ssl_cert }}"
    state: link
  when: not fake_ssl_cert and letsencrypt_cchq_ssl
  tags:
    - update-cert
    - letsencrypt

- name: Link CCHQ SSL Key
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{SITE_HOST}}/privkey.pem"
    dest: "{{ ssl_keys_dir }}/{{ nginx_ssl_key }}"
    state: link
  when: not fake_ssl_cert and letsencrypt_cchq_ssl
  tags:
    - update-cert
    - letsencrypt

- name: Link CAS SSL cert
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{CAS_SITE_HOST}}/fullchain.pem"
    dest: "{{ ssl_certs_dir }}/{{ cas_nginx_ssl_cert }}"
    state: link
  when: not fake_ssl_cert and CAS_SITE_HOST | default(None) and letsencrypt_cas_ssl
  tags:
    - link_ssl_cas

- name: Link CAS SSL Key
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{CAS_SITE_HOST}}/privkey.pem"
    dest: "{{ ssl_keys_dir }}/{{ cas_nginx_ssl_key  }}"
    state: link
  when: not fake_ssl_cert and CAS_SITE_HOST | default(None) and letsencrypt_cas_ssl
  tags:
    - link_ssl_cas

- name: Link PNA SSL cert
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{PNA_SITE_HOST}}/fullchain.pem"
    dest: "{{ ssl_certs_dir }}/{{ pna_nginx_ssl_cert }}"
    state: link
  when: not fake_ssl_cert and PNA_SITE_HOST | default(None)
  tags:
    - link_pna_cas

- name: Link PNA SSL Key
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{PNA_SITE_HOST}}/privkey.pem"
    dest: "{{ ssl_keys_dir }}/{{ pna_nginx_ssl_key  }}"
    state: link
  when: not fake_ssl_cert and PNA_SITE_HOST | default(None)
  tags:
    - link_pna_cas

- name: Link REACH SSL cert
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{REACH_SITE_HOST}}/fullchain.pem"
    dest: "{{ ssl_certs_dir }}/{{ reach_nginx_ssl_cert }}"
    state: link
  when: not fake_ssl_cert and REACH_SITE_HOST | default(None)
  tags:
    - link_ssl_reach

- name: Link REACH SSL Key
  become: yes
  file:
    src: "/etc/letsencrypt/live/{{REACH_SITE_HOST}}/privkey.pem"
    dest: "{{ ssl_keys_dir }}/{{ reach_nginx_ssl_key  }}"
    state: link
  when: not fake_ssl_cert and REACH_SITE_HOST | default(None)
  tags:
    - link_ssl_reach

# support for custom certs
- name: Copy cchq SSL cert
  become: yes
  copy:
    content: '{{ nginx_combined_cert_value }}'
    dest: "{{ ssl_certs_dir }}/{{ nginx_ssl_cert }}"
    mode: 0400
    owner: root
    group: root
  when: not fake_ssl_cert and nginx_combined_cert_value
  tags:
    - update-cert

- name: Copy cchq SSL Key
  become: yes
  copy:
    content: "{{ nginx_key_value }}"
    dest: "{{ ssl_keys_dir }}/{{ nginx_ssl_key }}"
    mode: 0400
    owner: root
    group: root
  no_log: true
  when: not fake_ssl_cert and nginx_key_value
  tags:
    - update-cert
