---

# Once we're entirely on bionic
# we might be able install from the default bionic apt repo
# and not add the official nginx repo.
# See: https://github.com/dimagi/commcare-cloud/pull/2901#pullrequestreview-250517794

- name: Add Nginx apt key
  become: yes
  apt_key: url=https://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx repository
  become: yes
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ bionic nginx' state=present

- name: Install nginx
  become: yes
  apt: name="nginx=1.17.3-1~bionic" state=present update_cache=yes cache_valid_time=3600
  notify: 'quick start nginx'

- meta: flush_handlers  # need to start nginx as quickly as possible for minimal downtime

- name: Make sure nofile ulimit is high
  become: yes
  lineinfile:
    path: /etc/default/nginx
    regexp: '^ULIMIT='
    line: 'ULIMIT="-n 65536"'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create sites-available and sites-enabled and allow cchq user to modify
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Create nginx http user
  become: yes
  user: name="{{ nginx_user }}" createhome=no password=no state=present groups="{{ cchq_user }}"

- name: Copy the nginx configuration file
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Copy the nginx default configuration file
  become: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Copy the nginx default site configuration file
  become: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx

- name: Create the link for site enabled specific configurations
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default force=yes
  notify: reload nginx

- name: Make sure the log directory exists
  import_tasks: roles/commcarehq/tasks/www_log_dir.yml

- set_fact: nginx_installed=True

