---

# Once we're entirely on bionic
# we might be able install from the default bionic apt repo
# and not add the official nginx repo.
# See: https://github.com/dimagi/commcare-cloud/pull/2901#pullrequestreview-250517794
- name: Add nginx repository
  become: yes
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install nginx
  become: yes
  apt: name="{{ nginx_ubuntu_pkg }}" state=latest update_cache=yes cache_valid_time=3600

- name: Make sure nofile ulimit is high
  become: yes
  lineinfile:
    path: /etc/default/nginx
    regexp: '^ULIMIT='
    line: 'ULIMIT="-n 65536"'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create nginx http user
  become: yes
  user: name="{{ nginx_user }}" createhome=no password=no state=present groups="{{ cchq_user }}"

- name: Create static files home
  become: yes
  file: path="{{ nginx_static_home }}" owner="{{ cchq_user }}" group="{{ cchq_user }}" mode=0755 state=directory

- name: Copy the nginx configuration file
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Copy the nginx default configuration file
  become: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Copy the nginx default site configuration file
  become: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: reload nginx

- name: Create the link for site enabled specific configurations
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default force=yes
  notify: reload nginx

- name: Allow cchq user to modify sites-availabled
  become: yes
  file:
    path: /etc/nginx/sites-available
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory

- name: Make sure the log directory exists
  import_tasks: roles/commcarehq/tasks/www_log_dir.yml

- set_fact: nginx_installed=True
