---
- name: check nginx configuration
  become: yes
  shell: "nginx -t"
  register: result
  check_mode: no
  failed_when: "result.rc != 0"

- name: restart the nginx service
  become: yes
  service: name=nginx state=restarted enabled=yes

- name: Assert nginx is running
  become: yes
  shell: 'service nginx status'
  register: nginx_status
  changed_when: false
  # new versions have `* nginx is running`, old have something containing `start/running`
  failed_when: nginx_status.rc != 0 or nginx_status.stdout.find('running') == -1
