---

- name: Create shared mount dir
  sudo: yes
  when: shared_drive_enabled
  file:
    path: "{{ shared_mount_dir }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: 0775
    state: directory
  tags:
    - nfs

- name: Mount directory in /etc/fstab
  sudo: yes
  when: shared_drive_enabled
  mount:
    name: "{{ shared_mount_dir }}"
    src: "{{ groups.shared_dir_host[0] }}:{{ shared_data_dir }}"
    fstype: nfs
    state: mounted
  tags:
    - nfs
