---

- name: Create shared data dir
  sudo: yes
  file:
    path: "{{ shared_data_dir }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  tags:
    - nfs
    - shared_files

- name: Format system data disk
  sudo: yes
  filesystem: fstype=ext4 dev={{ datadisk_device }}1
  when: datadisk_device is defined
  tags:
    - shared_files

- name: Mount system data disk
  sudo: yes
  mount: name={{ shared_data_dir }} src={{ datadisk_device }}1 fstype=ext4 state=mounted opts=defaults,noatime,nofail
  when: datadisk_device is defined
  tags:
    - shared_files

- name: Create shared directories
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - "{{ restore_payload_dir_host }}"
    - "{{ transfer_payload_dir_host }}"
    - "{{ shared_temp_dir_host }}"
  tags:
    - shared_files

- name: Create purging cron jobs
  sudo: yes
  cron:
    name: "{{ item.name }}"
    special_time: daily
    job: "find {{ item.dir }} -type f -maxdepth 1 -mtime +{{ item.max_age }} -delete"
    user: root
    cron_file: purge_cache_files
  with_items:
    - {name: 'Purge old restore files', dir: "{{ restore_payload_dir_host }}", max_age: 2}
    - {name: 'Purge old transfer files', dir: "{{ transfer_payload_dir_host }}", max_age: 2}
    - {name: 'Purge old temp files', dir: "{{ shared_temp_dir_host }}", max_age: 1}
  tags:
    - shared_files

- name: Add shared dir to exports
  sudo: yes
  when: shared_drive_enabled
  lineinfile:
    dest: /etc/exports
    line: "{{ shared_data_dir }} {{ item }}(rw,sync,all_squash,no_subtree_check,anongid={{ shared_dir_gid }})"
    regexp: "^{{ shared_data_dir }} {{ item }}"
    state: present
  with_flattened:
    - groups.webworkers
    - groups.proxy
    - groups.celery
    - groups.pillowtop
    - groups.shared_dir_host
  tags:
    - nfs

- name: Export directories
  sudo: yes
  when: shared_drive_enabled
  command: "exportfs -a"
  tags:
    - nfs
