secrets:
  ECRYPTFS_PASSWORD: 'xxBvYiMZ3YVIVkFR'
  KSPLICE_ACTIVATION_KEY:
  DATADOG_API_KEY: null
  DATADOG_APP_KEY: null
  AMQP_USER: "{{ deploy_env }}_worker"
  AMQP_PASSWORD: '******'
  SUPERVISOR_HTTP_USERNAME: user
  SUPERVISOR_HTTP_PASSWORD: 123
  POSTGRES_USERS:
    commcare:
      username: commcarehq
      password: LLkDYfDXbdnCzhgXMITCDs4s
    devreadonly:
      username: "devreadonly"
      password: devreadonly
      role_attr_flags: 'NOSUPERUSER,NOCREATEROLE,NOCREATEDB'
      privs:
        -
          privs: SELECT
          objs: ALL_IN_SCHEMA
    replication:
        username: 'hqrepl'
        password: 'hqrepl'
        role_attr_flags: 'LOGIN,REPLICATION'
    backup:
        username: 'hqbackup'
        password: 'hqbackup'
        role_attr_flags: 'SUPERUSER'

localsettings_private:
  COUCH_PASSWORD: p9RzGNx7wZr3BqLhNc7UtjQv
  COUCH_USERNAME: commcarehq
  SECRET_KEY: "JHX1y7iG0bQaVICcBXrQYw1fcJcomC24p6lxAfKMG0B5g7D5"
