blobdb_backup_dir: "{{ encrypted_root }}/backups/blobdb"
blobdb_dir_path: "{{ encrypted_root }}/blobdb"
backup_blobdb: False
blobdb_user: root
blobdb_backup_days: 2
blobdb_backup_weeks: 2
blobdb_s3: False
postgres_s3: False
couch_s3: False
blobdb_backup_hours: 1
blobdb_backup_hourly: False
