---
- name: check nginx configuration
  become: yes
  shell: "nginx -t"
  register: result
  always_run: true
  failed_when: "result.rc != 0"

- name: start the nginx service
  become: yes
  service: name=nginx state=started enabled=yes

- name: restart the nginx service
  become: yes
  service: name=nginx state=restarted enabled=yes

- name: Assert nginx is running
  become: yes
  shell: 'service nginx status'
  register: nginx_status
  changed_when: false
  failed_when: nginx_status.rc != 0 or nginx_status.stdout.find('start/running') == -1
