- name: Copy sudoers file
  become: true
  template: src=sudoers.j2 dest="/etc/sudoers.d/{{ ansible_control_user }}" validate='visudo -cf %s' owner=root group=root mode=0440

- name: create log file
  become: true
  file:
    path: /var/log/ansible.log
    mode: 0775
    owner: ansible
    group: "{{ dev_group }}"
    state: touch

- name: Pull commcare-cloud source
  become: yes
  become_user: "{{ item }}"
  git:
    repo: "{{ commcare_cloud_repository }}"
    dest: "/home/{{ item }}/commcare-cloud"
    version: "{{ commcare_cloud_version }}"
    recursive: yes
    accept_hostkey: yes
    update: no
  tags:
    - git
    - slow
  with_items: "{{ dev_users.present }}"

- name: install python env basics
  become: yes
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
    extra_args: '--ignore-installed six'

- name: Check whether init has been run
  become: yes
  become_user: "{{ item }}"
  command: "grep -q 'init-ansible' /home/{{ item }}/.profile"
  register: check_init
  check_mode: no
  changed_when: check_init.rc == 1
  failed_when: check_init.rc not in [ 0, 1 ]
  with_items: "{{ dev_users.present }}"

- name: run init script
  become: yes
  become_user: "{{ item.item }}"
  shell: "yes | bash commcare-cloud/control/init.sh"
  args:
    chdir: "/home/{{ item.item }}"
  when: item.rc != 0
  with_items: "{{ check_init.results }}"
  loop_control:
    label: "{{ item.item }}"
