---
- name: Check for uptrack installation
  become: yes
  shell: uptrack-show
  ignore_errors: yes
  register: command_result
  when: KSPLICE_ACTIVE
  changed_when: no

- name: Download install-uptrack
  become: yes
  get_url:
    url: https://www.ksplice.com/uptrack/install-uptrack
    dest: /tmp/install-uptrack
    mode: 0700
    owner: root
    group: root
  when: command_result|failed

- name: Install ksplice
  become: yes
  shell: /tmp/install-uptrack "{{ KSPLICE_ACTIVATION_KEY }}" --autoinstall
  when: command_result|failed

- name: Run uptrack upgrade
  become: yes
  shell: uptrack-upgrade -y
  when: command_result|failed
