---
# deploy-stack.yml

- import_playbook: update_apt_cache.yml
- import_playbook: deploy_common.yml
- import_playbook: deploy_lvm.yml
- import_playbook: deploy_db.yml
- import_playbook: deploy_commcarehq.yml
- import_playbook: deploy_proxy.yml
- import_playbook: deploy_shared_dir.yml
- import_playbook: deploy_webworker.yml
- import_playbook: deploy_formplayer.yml
- import_playbook: deploy_mailrelay.yml
- import_playbook: deploy_tmpreaper.yml
- import_playbook: deploy_etckeeper.yml
- import_playbook: deploy_airflow.yml
# migrate must happen before first fab
- import_playbook: migrate_on_fresh_install.yml
- import_playbook: deploy_http_proxy.yml
