---
- import_playbook: host_group_aliases.yml

- name: Deploys tmpreaper - removes files which haven't been accessed for a period of time
  hosts: all_commcarehq
  become: true
  roles:
    - role: tmpreaper
      tags: 'tmpreaper'
  tasks:
    - name: "Remove cron"
      cron:
        name: tmpreaper
        hour: "{{tmpreaper_cron_hour}}"
        minute: "{{tmpreaper_cron_minute}}"
        job: /usr/sbin/tmpreaper
        state: absent
      tags: 'tmpreaper'
