---

- import_playbook: common_db_machine_setup.yml
- import_playbook: run_postgresql.yml
- import_playbook: run_postgresql_backup.yml
- import_playbook: setup_standby_auth.yml
- import_playbook: run_couchdb.yml
- import_playbook: run_couchdb2.yml
- import_playbook: run_redis.yml
- import_playbook: run_elasticsearch.yml
- import_playbook: run_rabbitmq.yml
- import_playbook: run_zookeeper.yml
- import_playbook: run_kafka.yml
- import_playbook: install_java.yml
- import_playbook: move_logrotate.yml

