- name: Bootstrap Control
  hosts: "{{ target|default(control) }}"
  become: true
  gather_facts: true
  roles:
    - role: common
    - {role: ansible-control, tags: ansible-control}
    - role: ansible-logrotate
      logrotate_scripts:
        - name: control_ansible
          path: /var/log/ansible.log
          options:
            - size 10M
            - rotate 5
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - create
            - notifempty
