---
- name: Common Database Machine Setup
  hosts:
    - redis
    - elasticsearch
    - rabbitmq
    - formplayer
    - django_manage
  become: true
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}
    - {role: backups, tags: 'backups,backups-only'}

- name : PostgreSQL
  import_playbook: deploy_postgres.yml

- name : CitusDB
  import_playbook: deploy_citusdb.yml

- import_playbook: deploy_couchdb2.yml

- name: Redis
  hosts: redis
  become: true
  roles:
    - {role: redis, tags: 'redis'}

- name: MinIO
  hosts: minio
  become: true
  roles:
    - {role: minio, tags: 'minio'}

- name: Elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - {role: elasticsearch, tags: 'elasticsearch'}

- name: Redis Monitoring
  hosts: redis
  become: true
  roles:
    - redis_monitoring

- import_playbook: deploy_rabbitmq.yml
  tags:
    - rabbitmq

- import_playbook: deploy_kafka.yml
  tags:
    - kafka
    - zookeeper

# Note other machines also have java installed, but are initiated through the meta task
- name: Java
  become: true
  hosts:
    - celery
  roles:
    - {role: java, tags: java}

# Disables transparent huge pages (THP)
- name: Disable THP
  become: true
  hosts:
    - redis
    - elasticsearch
    - rabbitmq
    - formplayer
  tags:
    - kernel_tuning
    - after-reboot
  roles:
    - role: thp

- name: Move logrotate to hourly
  hosts:
    - proxy
  become: true
  roles:
    - role: logrotate
