---
roles:
  - src: git+https://github.com/andrewrothstein/ansible-couchdb.git
    version: fcb957ed038ab1c4fddcfef6b9c7617dcdeec9b7
    name: andrewrothstein.couchdb
  - src: git+https://github.com/dimagi/ansible-couchdb-cluster.git
    version: 7b4891860844b02243491cd501cc934626369783
    name: andrewrothstein.couchdb-cluster
  - src: git+https://github.com/ANXS/tmpreaper.git
    version: 46f8e0b8b8f5732eecc68b08b5e0c392c418e3f3
    name: tmpreaper
  - src: git+https://github.com/nickhammond/ansible-logrotate.git
    version: v0.0.5
    name: ansible-logrotate
  - src: DavidWittman.redis
    version: 1.2.7
  - src: sansible.logstash
    version: v2.4.0-latest
  - src: cloudalchemy.prometheus
    version: 2.15.5
  - src: cloudalchemy.alertmanager
    version: 0.19.0
  - src: cloudalchemy.grafana
    version: 0.17.0
  - src: cloudalchemy.node_exporter
    version: 0.21.5
  - src: bdellegrazie.postgres_exporter
    version: v4.1.0
  - src: gantsign.golang
    version: 2.3.1  

collections:
  - name: https://github.com/dimagi/commcare-logstash/releases/download/V0.9.5/dimagi-commcare_logstash-0.9.5.tar.gz
  - name: https://github.com/dimagi/commcare-prometheus/releases/download/V0.1.10/dimagi-commcare_prometheus-0.1.10.tar.gz
  - name: community.general
