- name: Rolling restart webworker services
  hosts: webworkers
  serial: ["10%", "30%", "50%", "100%"]
  become: true
  any_errors_fatal: true
  pre_tasks:
    - name: Decommission hosts
      import_role:
        name: deploy_hq
        tasks_from: commission_hosts
      vars:
        comment: true
  post_tasks:
    - name: Recommission hosts
      import_role:
        name: deploy_hq
        tasks_from: commission_hosts
      vars:
        comment: false
  tasks:
    - name: Restart
      command: supervisorctl {{ item }}
      register: stop_loop_hack
      when: not stop_loop_hack.failed | default(False)
      loop:
        - stop all
        - reread
        - update
        - start all
