- name: "Install Netvault Client"
  hosts: pg_standby:couchdb2
  become: true
  tasks:

    - name: "Download Netvault"
      get_url:
        url: "{{ netvault_url }}"
        dest: /tmp/netvault.tar.gz

    - name: "Unarchive Netvault"
      unarchive:
        src: /tmp/netvault.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: "Create symlink for lib64"
      file:
        src: /usr/lib
        dest: /usr/lib64
        state: link

    - name: "Runs install script"
      expect:
        chdir: /tmp/netvault/
        command: /tmp/netvault/install
        responses:
          'Select a Language': '' # send Enter for English
          '(.*)terms of the license(.*)': 'y' # Accept
          '(.*)Where should NetVault be installed(.*)': '' # default /usr/netvault
          '(.*)Please enter a NetVault machine name(.*)': '' # default hostname
          'Please enter the NetVault password for this machine': "{{ netvault_password }}"
          'Please confirm password': "{{ netvault_password }}"
