---
# deploy-stack.yml

- name: update apt cache
  hosts: all
  gather_facts: no
  sudo: yes
  tasks:
    - apt: update_cache=true cache_valid_time=3600
  tags:
    - common
    - aptcache

- include: deploy_common.yml tags=common
- include: deploy_db.yml
- include: deploy_commcarehq.yml
- include: deploy_proxy.yml
- include: deploy_shared_dir.yml
- include: deploy_webworker.yml
- include: deploy_touchforms.yml
- include: deploy_formplayer.yml
