- name: CommcareHQ
  hosts:
   - webworkers
   - touchforms
   - formplayer
   - celery
   - proxy
   - pillowtop
   - postgresql
   - couchdb2_proxy
  become: true
  roles:
    - {role: commcarehq, tags: commcarehq}

- name: Celery cron jobs for HQ
  hosts:
    - celery
  become: true
  roles:
    - role: tmpreaper
      tags: commcarehq, celery_hq, tmpreaper, cron
      tmpreaper_time: '2d'
