---
# deploy-stack.yml

- name: update apt cache
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - apt: update_cache=true cache_valid_time=3600
  tags:
    - common
    - aptcache

- import_playbook: deploy_common.yml tags=common
- import_playbook: deploy_lvm.yml
- import_playbook: deploy_db.yml
- import_playbook: deploy_commcarehq.yml
- import_playbook: deploy_proxy.yml
- import_playbook: deploy_shared_dir.yml
- import_playbook: deploy_webworker.yml
- import_playbook: deploy_touchforms.yml
- import_playbook: deploy_mailrelay.yml
- import_playbook: deploy_tmpreaper.yml
- import_playbook: deploy_etckeeper.yml

- import_playbook: deploy_formplayer.yml
  when: touchforms_enabled|default(False)
