---

- name: Keystore
  hosts: webworkers
  sudo: yes
  roles:
    - {role: keystore, tags: keystore}

- name: Webworkers
  hosts: webworkers
  sudo: yes

# There used to be some code here for updating workers one by one
# but it's not functionally useful until we're off fab deploy and makes things
# look back to commit 94b08e0390bb031dd048804ce5a9c8dfcfeccbc1 if you want it
