---
- hosts: all
  tasks:
    - name: Set password
      sudo: yes
      user: name={{user}} state=present password={{password}}

  vars_prompt:
    - name: user
      prompt: Username
      private: no
    # is there a way to check that this is non-empty?
    - name: password
      prompt: 'New password'
      private: yes
      encrypt: sha512_crypt
      confirm: yes
