airflow_home: "{{ cchq_home }}/airflow"
airflow_code_dir: "{{ airflow_home }}/pipes"
airflow_dag_dir: "{{ airflow_home }}/dags"
airflow_version: "master"
airflow_repository: https://github.com/dimagi/pipes.git
airflow_virtualenv: "{{ airflow_home }}/env"

