
- name: Copy Elasticsearch logging config
  become: yes
  template:
    src: config/logging.yml.j2
    dest: "{{ elasticsearch_conf_dir }}/logging.yml"
    owner: elasticsearch
    group: elasticsearch
  register: copy_elasticsearch_logging_result
  tags:
    - es_conf

- name: Disable Java Heap Dump
  replace:
    path: "{{ elasticsearch_home }}/bin/elasticsearch.in.sh"
    regexp: '^JAVA_OPTS="\$JAVA_OPTS -XX:\+HeapDumpOnOutOfMemoryError"'
    replace: '#JAVA_OPTS="$JAVA_OPTS -XX:+HeapDumpOnOutOfMemoryError"'

- name: Install elasticsearch python client
  become: yes
  pip:
    name: elasticsearch>=2.0.0,<3.0.0
  when: elasticsearch_version == '2.4.6'


- name: Check for installed plugins
  shell: "{{ elasticsearch_home }}/bin/plugin list"
  register: installed_plugins

- name: Install elasticsearch aws plugin
  become: yes
  shell: "{{ elasticsearch_home }}/bin/plugin install elasticsearch/elasticsearch-cloud-aws/{{ aws_plugin_version }}"
  when: (backup_es_s3) and (installed_plugins.stdout is defined) and ('cloud-aws' not in installed_plugins.stdout) and elasticsearch_version == '1.7.6'
  
- name: Install elasticsearch aws plugin
  become: yes
  shell: "{{ elasticsearch_home }}/bin/plugin install cloud-aws"
  when: (backup_es_s3) and (installed_plugins.stdout is defined) and ('cloud-aws' not in installed_plugins.stdout) and elasticsearch_version == '2.4.6'

- name: Install elasticsearch swift plugin
  become: yes
  shell: "{{ elasticsearch_home }}/bin/plugin install https://github.com/dimagi/elasticsearch-repository-swift/releases/download/swift-repository-plugin-{{ swift_plugin_version }}/repository-swift-3.0.0-es{{ swift_plugin_version }}.zip"
  when: (backup_es_swift) and (installed_plugins.stdout is defined) and ('repository-swift' not in installed_plugins.stdout) and elasticsearch_version == '2.4.6'