app_name: commcarehq
supervised_tasks:
  - name: "{{ app_name }}-{{ deploy_env }}-formsplayer"
    config:
      command: "java -Xmx2048m -Xss1024k -classpath {{ jython_home }}/jython.jar: -Dpython.home={{ jython_home }} -Dpython.executable={{ jython_home }}/bin/jython org.python.util.jython {{ code_home }}/submodules/touchforms-src/touchforms/backend/xformserver.py"
      user: "{{ cchq_user }}"
      autostart: true
      autorestart: true
      stdout_logfile: "{{ log_home }}/formsplayer.log"
      redirect_stderr: true
      stderr_logfile: "{{ log_home }}/formsplayer.error.log"
