- name: Add New Relic apt repo
  apt_repository: repo="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present
  register: add_new_relic_repo

- name: Add New Relic apt key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Update package list
  apt: update_cache=yes
  when: add_new_relic_repo is changed

- name: Install newrelic-sysmond
  apt: name=newrelic-sysmond state=present

- name: Set New Relic license key
  command: 'nrsysmond-config --set license_key={{ NEW_RELIC_KEY }}'

- name: Make sure newrelic-sysmond has started
  service: name=newrelic-sysmond state=started
  tags: after-reboot

- name: copy newrelic ini file
  template:
    src: newrelic.ini.j2
    dest: "{{ www_home }}/newrelic.ini"
    group: cchq
    owner: cchq
    mode: 0755
