- name: Copy blobdb backup script
  sudo: yes
  template:
    src: "create_blobdb_backup.sh.j2"
    dest: "/etc/cron.d/create_blobdb_backup.sh"
    group: root
    owner: root
    mode: 0700
    backup: yes
  when: backup_blobdb

- name: Create Daily Cron job
  sudo: yes
  cron:
    name: "Backup blobdb daily"
    job: "/etc/cron.d/create_blobdb_backup.sh daily 3"
    minute: 0
    hour: 0
    weekday: "1,2,3,4,5,6"
    user: blobdb
    cron_file: backup_blobdb
  when: backup_blobdb

- name: Create Weekly Cron job
  sudo: yes
  cron:
    name: "Backup blobdb weekly"
    job: "/etc/cron.d/create_blobdb_backup.sh weekly 21"
    minute: 0
    hour: 0
    weekday: 0
    user: blobdb
    cron_file: backup_blobdb
  when: backup_blobdb
