---
nginx_sites:
- server:
   balancers:
    - name: "{{ deploy_env }}_commcare"
      hosts: "{{ groups['hq_webworkers'] | default('webworkers') }}"
      port: "{{ django_port }}"
    - name: "{{ deploy_env }}_commcare_submissions"
      hosts: "{{ groups['mobile_webworkers'] | default('webworkers') }}"
      port: "{{ django_port }}"
    - name: "{{ deploy_env }}_formplayer"
      hosts: formplayer
      port: "{{ formplayer_port }}"
      # hash off formplayer_session cookie or X-FORMPLAYER-SESSION header
      # Note: this assumes only one of the two is present in any given request.
      # (If a request sends _both_, that will break sticky routing
      # unless it's done perfectly consistently. Please don't!)
      method: "hash $cookie_formplayer_session$http_x_formplayer_session consistent"
   proxy_cache_path:
    - name: "hq_media_cache"
      path: "{{ www_home }}/hq_media/cache"
      max_size: "2g"
      inactive_time: "24h"
   file_name: "{{ deploy_env }}_commcare"
   listen: "443 ssl http2{{ ' default_server' if deploy_env == primary_ssl_env else '' }}"
   root: "/var/www/html"
   server_name: "{{ SITE_HOST }}{% if ALTERNATE_HOSTS %} {{ ALTERNATE_HOSTS | join(' ') }}{% endif %}"
   client_max_body_size: 600m
   proxy_max_temp_file_size: 5120m
   proxy_set_headers:
   - "Host $host"
   - "X-Forwarded-For $remote_addr"
   - "X-Forwarded-Protocol  $scheme"
   access_log: "{{ log_home }}/{{ deploy_env }}-timing.log timing"
   locations:
    - name: /
      balancer: "{{ deploy_env }}_commcare"
      proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 1200s # 900s temporarily increase timeout for UCR data exports for ICDS
      proxy_buffers: 8 64k
      proxy_buffer_size: 64k
      client_body_buffer_size: 512k
    - name: '~ /a/[^/]+/(receiver|phone)/'
      balancer: "{{ deploy_env }}_commcare_submissions"
      proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 900s
      proxy_buffers: 8 64k
      proxy_buffer_size: 64k
      client_body_buffer_size: 512k
    - name: "/static"
      alias: "{{ nginx_static_home }}"
      add_header: "Access-Control-Allow-Origin *"
      expires: "1M"
      try_files: "$uri $uri/index.html $uri/ =404"
    - name: "/{{ transfer_payload_dir_name }}"
      alias: "{{ shared_mount_dir if shared_drive_enabled else shared_data_dir }}/{{ transfer_payload_dir_name }}"
      is_internal: True
    - name: /errors
      alias: "{{ errors_home }}/pages"
    - name: /ws
      proxy_pass: "http://unix:{{ www_home }}/web.socket"
      proxy_http_version: "1.1"
      proxy_set_headers:
      - "Upgrade $http_upgrade"
      - "Connection \"upgrade\""
    - name: /formplayer
      balancer: "{{ deploy_env }}_formplayer/"
      proxy_next_upstream_tries: "{{ 3 if formplayer_shared_drive else 1 }}"
      proxy_read_timeout: 900s
    - name: "/hq/multimedia/file"
      balancer: "{{ deploy_env }}_commcare"
      proxy_redirect: "http://{{ SITE_HOST }} https://{{ SITE_HOST }}"
      proxy_next_upstream_tries: 1
      proxy_read_timeout: 900s
      proxy_cache: hq_media_cache
   extra_locations: "{{ site_locations|default([]) }}"
