---
nginx_ssl_cert: "{{ pna_nginx_ssl_cert }}"
nginx_ssl_key:  "{{ pna_nginx_ssl_key }}"

nginx_sites:
- server:
   balancers:
    - name: "{{ deploy_env }}_pna_commcare"
      hosts: webworkers
      port: "{{ django_port }}"
    - name: "{{ deploy_env }}_pna_formplayer"
      hosts: formplayer
      port: "{{ formplayer_port }}"
      method: "hash $cookie_sessionid consistent"
   mappings:
    - name: "$digest_submission"
      variable: "$http_authorization"
      value: "$server_name"
   limit_req_zones:
    - name: "submissions"
      zone: "$digest_submission"
      rate: "50r/s"
   file_name: "{{ deploy_env }}_pna_commcare"
   listen: "443 ssl http2 default_server"
   server_name: "{{ PNA_SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_headers:
   - "Host $host"
   - "X-Forwarded-For $remote_addr"
   - "X-Forwarded-Protocol  $scheme"
   add_header: "X-Frame-Options SAMEORIGIN"
   access_log: "{{ log_home }}/{{ deploy_env }}-timing.log timing"
   locations:
     - name: /
       balancer: "{{ deploy_env }}_pna_commcare"
       proxy_redirect: "http://{{ PNA_SITE_HOST }} https://{{ PNA_SITE_HOST }}"
       proxy_next_upstream_tries: 1
       proxy_read_timeout: 900s
       client_body_buffer_size: 512k
     - name: "/static"
       alias: "{{ nginx_static_home }}"
       add_header: "Access-Control-Allow-Origin *"
       expires: "1M"
       try_files: "$uri $uri/index.html $uri/ =404"
     - name: "/{{ transfer_payload_dir_name }}"
       alias: "{{ shared_mount_dir if shared_drive_enabled else shared_data_dir }}/{{ transfer_payload_dir_name }}"
       is_internal: True
     - name: /errors
       alias: "{{ errors_home }}/pages"
     - name: /ws
       proxy_pass: "http://unix:{{ www_home }}/web.socket"
       proxy_http_version: "1.1"
       proxy_set_headers:
       - "Upgrade $http_upgrade"
       - "Connection \"upgrade\""
     - name: /formplayer
       balancer: "{{ deploy_env }}_pna_formplayer/"
       proxy_next_upstream_tries: 1
       proxy_read_timeout: 900s
     - name: '~ /a/[^/]+/(receiver|phone)/'
       proxy_next_upstream_tries: 1
       proxy_buffers: 8 64k
       proxy_buffer_size: 64k
       client_body_buffer_size: 512k
       limit_reqs:
         - zone_name: "submissions"
           burst: 100
           nodelay: True
