---
nginx_sites:
- server:
    balancers:
      - name: "{{ deploy_env }}_riakcs_{{ riakcs_proxy_port }}"
        hosts: "{{ hosts_group }}"
        port: "{{ riakcs_port }}"
    file_name: "{{ deploy_env }}_riakcs_{{ riakcs_proxy_port }}"
    listen: "{{ riakcs_proxy_port }}"
    # boto3 python library switches to multipart uploads for blobs > 8M
    client_max_body_size: "9M"
    client_body_buffer_size: "128k"
    upstream_port: "{{ riakcs_port }}"
    proxy_set_headers:
      - "Host $host"
      - "X-Real-IP $remote_addr"
    locations:
      - name: /
        balancer: "{{ deploy_env }}_riakcs_{{ riakcs_proxy_port }}"
        proxy_redirect: ' off'
        proxy_connect_timeout: 90
        proxy_send_timeout: 90
        proxy_read_timeout: 90
        proxy_buffer_size: 64k
        proxy_buffers: 8 64k
        # http_403 from Riak CS is an indication that Riak is down
        proxy_next_upstream: error timeout http_403
        proxy_next_upstream_tries: 3
